In [32]:
import core
import pandas as pd

In [33]:
import pandas as pd
reddit_data = pd.read_csv('reddit_database_sentiment.csv', sep=';',low_memory = False)

## TEST 1: Preprocesar Texto

In [34]:
print(reddit_data['post'].astype(str).apply(core.preprocess_post)[:10])

0    theres lot reasons want know stuff figured id ...
1    im cross posting rcyberlaw hopefully guys find...
2    dotceda functional analytics consultant offeri...
3    program details data analytics certification c...
4    decided grad school physics branching job mark...
5    data analytics provides insight interpretation...
6    dieser artikel soll weniger die leistung oder ...
7    apparent reason ive relatively huge spike traf...
8    anyone experience client asking implementation...
9    hey gf trouble ga hasnt gotten response days p...
Name: post, dtype: object

## TEST 2: Clasificacion Subreddit

In [35]:
# Preprocesar los datos
reddit_data['clean_post'] = reddit_data['post'].astype(str).apply(core.preprocess_post)

#prueba
input_text = reddit_data['post'][224811]
result = core.train_and_classify_subreddit(reddit_data, input_text)
print(result)

MachineLearning

## TEST 3: Extracción Datos

sin preprocesamiento

In [36]:
pd.options.display.max_columns = None
pd.options.display.max_rows = 50
df = pd.read_csv('reddit_database_sentiment.csv',sep=';',usecols=['post'],dtype={'post':pd.StringDtype()}) #leen los post y creamos un dataframe
texto = df['post']
core.find_subreddit_mentions(texto)

['/r/cyberlaw',
 '/r/stopdrinking',
 '/r/analytics',
 '/r/userexperience',
 '/r/15i7sde',
 '/r/Analytics',
 '/r/RealEstateTechnology',
 '/r/techsupport',
 '/r/socialmedia',
 '/r/oculus',
 '/r/SideProject',
 '/r/exmormon',
 '/r/Entrepreneur',
 '/r/piwik',
 '/r/bigseo',
 '/r/PPC',
 '/r/ppc',
 '/r/webdev',
 '/r/analytics!',
 '/r/RJ2BQ75',
 '/r/adops',
 '/r/science',
 '/r/callofdutyworldwartwo',
 '/r/seo',
 '/r/marketing',
 '/r/webmarketing',
 '/r/advertising',
 '/r/DataSciencewithR',
 '/r/collect?v=1&amp;_v=j73&amp;a=213050344&amp;t=pageview&amp;_s=1',
 '/r/Wordpress',
 '/r/wordpress',
 '/r/dataisbeautiful',
 '/r/learnprogramming',
 '/r/GoogleAnalytics',
 '/r/data_warehousing',
 '/r/analytics&amp;message=Suggestion',
 '/r/BusinessIntelligence',
 '/r/AskReddit',
 '/r/datascience',
 '/r/bigdata',
 '/r/excel',
 '/r/tableau',
 '/r/dataanalysis',
 '/r/ModernDataStack',
 '/r/t',
 '/r/GoogleOptimize',
 '/r/bipp',
 '/r/machinelearning',
 '/r/tensorflow',
 '/r/MachineLearning',
 '/r/deeplearning',
 '/r/Mathematica',
 '/r/learnmachinelearning',
 '/r/PRML_reading',
 '/r/aijournal',
 '/r/MLIndia',
 '/r/MachineLearning:',
 '/r/T32MPWD',
 '/r/cscareerquestions',
 '/r/computervision',
 '/r/ai',
 '/r/ai_music',
 '/r/nvidia',
 '/r/LightWarriorAscension',
 '/r/MachineLearningKeras',
 '/r/deeplearning**',
 '/r/learnpython',
 '/r/IdiotsInCars',
 '/r/2D3DAI',
 '/r/GPT3',
 '/r/GPU',
 '/r/BrainInspired',
 '/r/reasonal',
 '/r/Futurology',
 '/r/ML_Eng',
 '/r/ML_End',
 '/r/neuralthreads',
 '/r/nebuly',
 '/r/plutus',
 '/r/',
 '/r/datascience!',
 '/r/DataScience',
 '/r/statistics',
 '/r/bigdatajobs',
 '/r/Guitar',
 '/r/titlegore',
 '/r/Datascience',
 '/r/GradSchool',
 '/r/compsci',
 '/r/GameAnalytics',
 '/r/DataSci',
 '/r/forhire',
 '/r/IPython',
 '/r/childfree',
 '/r/IAmA',
 '/r/MQF8DW5',
 '/r/datamining',
 '/r/Seattle',
 '/r/datasciencecareerquestions',
 '/r/Python',
 '/r/BigDataJobs',
 '/r/Manonamustard',
 '/r/SnakeOiler:',
 '/r/datasciencestudygroup',
 '/r/datasets',
 '/r/DailyDataScience',
 '/r/bioinformatics',
 '/r/PrimeiraLiga',
 '/r/Austin',
 '/r/math',
 '/r/applyingtocollege',
 '/r/ApplyingToCollege',
 '/r/dailyprogrammer',
 '/r/DataScienceSimplified',
 '/r/learnmath',
 '/r/LearningLinearAlgebra',
 '/r/ML',
 '/r/gatech',
 '/r/DataScienceJobs',
 '/r/pystats',
 '/r/politics',
 '/r/HailCorporate',
 '/r/askreddit',
 '/r/fatFIRE',
 '/r/Resumes',
 '/r/Vive',
 '/r/SQL',
 '/r/dscareerquestions',
 "/r/learnprogramming's",
 '/r/DataScience!',
 '/r/datascience!**',
 '/r/explainlikeimfive',
 '/r/rstats',
 '/r/BigDataHPC',
 '/r/datascience:',
 '/r/confession',
 '/r/RXGQWKG',
 '/r/esp8266',
 '/r/coursera',
 '/r/medical',
 '/r/medical_datascience',
 '/r/javascript',
 '/r/MLQuestions',
 "/r/CollegeBasketball's",
 '/r/CollegeBasketball',
 '/r/pics',
 '/r/dataisbeautiful;',
 '/r/dataengineering',
 '/r/dataisbeatiful',
 '/r/GoogleTagManager',
 '/r/devops',
 '/r/CSCareerQuestions',
 '/r/datascienceproject',
 '/r/roastme',
 '/r/australia',
 '/r/VisualSchool',
 '/r/AcademicPsychology',
 '/r/MLsurvey12',
 '/r/laptops',
 '/r/googlecolabnotebooks',
 '/r/careerguidance',
 '/r/ACT',
 '/r/videos',
 '/r/worldnews',
 '/r/rbeginner',
 '/r/AskAcademia',
 '/r/gradadmissions',
 '/r/3S3FY8L',
 '/r/TXXHGPR',
 '/r/PostgreSQL',
 '/r/DataIsBeautiful',
 '/r/QFQJH7V',
 '/r/TheRedditNation',
 '/r/gis',
 '/r/NexusAurora',
 '/r/loseit',
 '/r/ml',
 '/r/ml_dotnet',
 '/r/buildapc',
 '/r/programming',
 '/r/learndatascience',
 '/r/freeflight',
 '/r/Rlanguage',
 '/r/rprogramming',
 '/r/maps',
 '/r/SpreadsheetGeeks',
 '/r/doc',
 '/r/bQxm4P',
 '/r/aws',
 '/r/AskStatistics',
 '/r/FinancialCareers',
 '/r/7MLYCPT',
 '/r/JSBQNBR',
 '/r/depression',
 '/r/SuicideWatch',
 '/r/de',
 '/r/gooddata',
 '/r/ExcelTips_ActiveGroup',
 '/r/NoCodeSaaS',
 '/r/LPM1JR4MNp',
 '/r/forecasting',
 '/r/reactjs',
 '/r/ProductManagement',
 '/r/PVwiJDNntW',
 '/r/PVwiJDNntW?fbclid=IwAR02RgrXHig1d1wxDVwno9RHVT3IpvnsTU_c5gmCR46N-k37OsO4ubSbYVU',
 '/r/socceranalytics',
 '/r/reinforcementlearning',
 '/r/articles',
 '/r/nextfuckinglevel',
 '/r/XNBtPNqVan**',
 '/r/XNBtPNqVan',
 '/r/dataisbeuatifulButWeShowedItInTheWorseWayPossible',
 '/r/RocketLeague',
 '/r/HomeworkHelp',
 '/r/NannyML-state-of-MLOps',
 '/r/chess',
 '/r/P2MG8JK',
 '/r/sql',
 '/r/data',
 '/r/Resume',
 '/r/askmath',
 '/r/Eldenring',
 '/r/Visualization',
 '/r/visualization',
 '/r/datasets!',
 '/r/BioDatasets',
 '/r/Datasets',
 '/r/proofreading',
 '/r/estimation',
 '/r/sna',
 '/r/findareddit',
 '/r/ComputerScience',
 '/r/healthIT',
 '/r/europe',
 '/r/news',
 '/r/news:',
 '/r/hacking',
 '/r/bigquery',
 '/r/rape',
 '/r/opendata',
 '/r/anonymous',
 '/r/paradoxplaza',
 '/r/random',
 '/r/counting',
 '/r/whatsthisplant',
 '/r/nba',
 '/r/security',
 '/r/BuyItForLife',
 '/r/Dataset',
 '/r/politics-users',
 '/r/the_donald',
 '/r/enoughtrumpspam',
 '/r/beards',
 '/r/SomebodyMakeThis',
 '/r/scifi',
 '/r/Stuck_in_the_Matrix',
 '/r/ForeverAlone',
 '/r/flairer',
 '/r/Flairer',
 '/r/gaming',
 '/r/korean',
 '/r/technology',
 '/r/journalism',
 '/r/economics',
 '/r/4chan4trump',
 '/r/4chan4Trump',
 '/r/mapporn',
 '/r/Surveydatasets',
 '/r/pushshift',
 '/r/threatintel',
 '/r/glassine',
 '/r/DataVizRequests',
 '/r/abdulrazak123',
 '/r/dataset',
 '/r/announcements',
 '/r/r4r',
 '/r/dota2',
 '/r/dota2facsinadvice',
 '/r/LanguageTechnology',
 '/r/rateme',
 '/r/nfl',
 '/r/semanticweb',
 '/r/297RWG7',
 '/r/hongkong',
 '/r/dfp',
 '/r/dfv',
 '/r/dfm',
 '/r/DataHoarder',
 '/r/Kundalini',
 '/r/SecurityAnalysis',
 '/r/ListOfSubreddits',
 '/r/youtube',
 '/r/redditdev',
 '/r/aoe2',
 '/r/neuralnetworks',
 '/r/mlpapers',
 '/r/MachinesLearn',
 '/r/datacleaning',
 '/r/artificial',
 '/r/algotrading',
 '/r/mexico',
 '/r/espana',
 '/r/argentina',
 '/r/ParlerWatch',
 '/r/showerthoughts',
 '/r/webscrapping',
 '/r/wallstreetbets',
 '/r/AskScience',
 '/r/touhou',
 '/r/pokemon',
 '/r/Marketresearch',
 '/r/MarketingResearch',
 '/r/csv',
 '/r/Antiwork',
 '/r/nursing',
 '/r/place',
 '/r/Place',
 '/r/redditdata',
 '/r/SZLPRp',
 '/r/SampleSize',
 '/r/BOFBlt',
 '/r/meirl',
 '/r/me_irl',
 '/r/KaggleExchange',
 '/r/pytorch',
 '/r/ELI5',
 '/r/LearnMachineLearning',
 '/r/LY29GM5',
 '/r/cs231n',
 '/r/robotics',
 '/r/botwatch',
 '/r/thing',
 '/r/LML',
 '/r/stats',
 '/r/projects',
 '/r/?url=https%3A%2F%2Fyoutu',
 '/r/factorio',
 '/r/AssemblyLineGame',
 '/r/TheoryOfReddit',
 '/r/Enhancement"',
 '/r/KerasML',
 '/r/JS',
 '/r/sysadmin',
 '/r/win-32',
 '/r/noarch',
 '/r/slavelabour',
 '/r/ProgrammingTasks',
 '/r/stocks',
 '/r/lml:',
 '/r/java',
 '/r/LearnMachineLearning!',
 '/r/FOO',
 '/r/liberal',
 '/r/conservative',
 '/r/legaladviceofftopic',
 '/r/DecisionTheory',
 '/r/investing',
 '/r/AskComputerScience',
 '/r/dreams',
 '/r/elitepcmasterrace',
 '/r/cluster-mixed-types',
 '/r/genetic_algorithms',
 "/r/machinelearning's",
 '/r/5TTSXWX',
 '/r/csharp',
 '/r/opensource',
 '/r/LAForSanders',
 '/r/great-expectations-hackathon-3',
 '/r/Reasonal',
 '/r/FreeCourses_coupons',
 '/r/neuroscience',
 '/r/python',
 '/r/9XDC8Q2',
 '/r/sliced-ml',
 '/r/GabbyPetito',
 '/r/learnmachinelearning!',
 '/r/opencv',
 '/r/edenai',
 '/r/Bayes',
 '/r/mltraders',
 '/r/MindSporeOSS',
 '/r/Unexpected',
 '/r/soccer',
 '/r/DSP',
 '/r/ML!',
 '/r/machinelearning!',
 '/r/philately',
 '/r/bicycling',
 '/r/motorcycles',
 '/r/maths',
 '/r/EDMit',
 '/r/MLCoursera',
 '/r/Physics',
 '/r/actuary',
 '/r/machinelearning--',
 '/r/OpenDataScience',
 '/r/machinelearning*',
 '/r/informationretrieval',
 '/r/Showerthoughts',
 '/r/machineLearning',
 '/r/jobs',
 '/r/TheButton',
 '/r/gamedev',
 '/r/neuro',
 '/r/singularity',
 '/r/thisisthewayitwillbe',
 '/r/askstatistics',
 '/r/tagpro',
 '/r/mlMoves',
 '/r/mlclass',
 '/r/machineleaning',
 '/r/datasciencejobs',
 '/r/MachineLearning!',
 '/r/evolutionarycomp',
 '/r/fitness',
 '/r/machinelearning?',
 '/r/deepstyle',
 '/r/teslamotors',
 '/r/mlstudygroup',
 '/r/IAmA!',
 '/r/hearthstone',
 '/r/MLquestions',
 '/r/statML',
 '/r/askcience',
 '/r/algorithms',
 '/r/cars',
 '/r/cars?',
 '/r/machinelearning?"',
 '/r/languagetechnology',
 '/r/Damnthatsinteresting',
 '/r/MLjobs',
 '/r/pcmasterrace',
 '/r/philosophy',
 '/r/askphilosophy',
 '/r/AIethics',
 '/r/RoboCup',
 '/r/LeagueofLegends',
 '/r/leagueoflegends',
 '/r/2007scape',
 '/r/badhistory',
 '/r/badphilosophy',
 '/r/The_Donald',
 '/r/Machinelearning!',
 '/r/circlejerk',
 '/r/linguistics',
 '/r/gradschool',
 '/r/mlyearning',
 "/r/MachineLearning's",
 '/r/nn4ml',
 '/r/StarWarsBattlefront',
 '/r/ML:',
 '/r/MachineLarning',
 '/r/onoff',
 '/r/DotA2',
 '/r/AIJournalism',
 '/r/stanford',
 '/r/language_exchange',
 '/r/haskell*',
 '/r/kbobrowski',
 '/r/cbaduk',
 '/r/Julia',
 '/r/futurology',
 '/r/MLPapersQandA',
 '/r/settings',
 '/r/choosingbeggars',
 '/r/reactnative',
 '/r/MachineLearningLounge',
 '/r/VWH67QW',
 '/r/GJ5593H',
 '/r/u_lonely_perceptron',
 '/r/MLQuestions!',
 '/r/Amd',
 '/r/PHP',
 '/r/MediaSynthesis',
 '/r/ml_tips',
 '/r/DataScienceArticles',
 '/r/ArtificialNotes',
 '/r/DataScienceNotes',
 '/r/deeplearnings',
 '/r/MachineLearningNotes',
 '/r/OrhunProject',
 '/r/uncannyvalley',
 '/r/AIfreakout',
 '/r/Defcon',
 '/r/compmathneuro',
 '/r/PDGXBM5',
 '/r/literotica',
 '/r/SubSimulatorGPT2',
 '/r/legaladvice',
 '/r/amitheasshole',
 '/r/writingprompts',
 '/r/relationships',
 '/r/electronics',
 '/r/watches',
 '/r/askscience',
 '/r/btc',
 '/r/MachineLearning**',
 '/r/QuantumComputing',
 '/r/rthosfeltcmu',
 '/r/chanceme',
 '/r/EarthPorn',
 '/r/computerscience',
 '/r/LearnRLearning',
 '/r/LatestInML',
 '/r/SubSimulatorGPT2Meta',
 '/r/XRRPDBF',
 '/r/TensorFlowJS',
 '/r/matlab',
 '/r/SCP',
 '/r/RemindMeBot',
 '/r/aigeneratedmemes',
 '/r/SubSimGPT2Interactive',
 '/r/GAYDETECTOR',
 '/r/AskHistorians',
 '/r/ProgrammerHumor',
 '/r/generative',
 '/r/ArtificialInteligence',
 '/r/OpenAI',
 '/r/academia',
 '/r/SoftwareEngineering',
 '/r/smashbros',
 '/r/apple',
 '/r/DukeDBTData',
 '/r/polandball',
 '/r/MathStats',
 '/r/nature',
 '/r/unique-ai-method-for-generating-proteins-will-speed-up-drug-development',
 '/r/wigglegrams',
 '/r/HomePod',
 '/r/poker',
 '/r/RedditEng',
 '/r/blueiris',
 '/r/kmeans-free-lunch',
 '/r/SelfDrivingCars',
 '/r/bubling',
 '/r/pXtfUKWUDA',
 '/r/cpp',
 '/r/bigsleep',
 '/r/sRf3pFBLLq',
 '/r/R9BL1szeei',
 '/r/Animesuggest',
 '/r/booksuggestions',
 '/r/MovieSuggestions',
 '/r/MachineLearningDervs',
 '/r/csMajors',
 '/r/music',
 '/r/vibereach',
 '/r/TheAxis',
 '/r/xVFu2f8qrJ',
 '/r/AI4Finance',
 '/r/AI4Finance_FinRL',
 '/r/dalle2',
 '/r/funny',
 '/r/statistics!',
 '/r/biology',
 '/r/stats?',
 '/r/Statistics',
 '/r/stats:',
 '/r/r',
 '/r/homework',
 '/r/engineering',
 '/r/5wmerq',
 '/r/anime',
 '/r/Fitness',
 '/r/homeworkhelp',
 '/r/econometrics',
 '/r/cheatatmathhomework',
 '/r/statistic',
 '/r/Sabermetrics',
 '/r/tall',
 '/r/math?',
 '/r/UnresolvedMysteries',
 '/r/library',
 '/r/TwitchPlaysPokemon',
 '/r/twitchplayspokemon',
 '/r/Journal_Club',
 '/r/space',
 '/r/cogsci',
 '/r/MensRights',
 '/r/quiteinteresting',
 '/r/iama',
 '/r/IAMA',
 '/r/reddit',
 '/r/environment',
 '/r/350',
 '/r/divestment',
 '/r/dogecoin',
 '/r/nascar',
 '/r/misophonia',
 '/r/audiophile',
 '/r/bugs',
 '/r/nrl',
 '/r/TheRedPill',
 '/r/HPMOR',
 '/r/Excel',
 '/r/spss',
 '/r/MMA',
 '/r/resumes',
 '/r/TIFU',
 '/r/tifu',
 '/r/Tagpro',
 '/r/statstics',
 '/r/programminghorror',
 '/r/cricket',
 '/r/EVEX',
 '/r/button',
 '/r/ScienceTheButton',
 '/r/collegebasketball',
 '/r/MachineLearning?',
 '/r/dae',
 '/r/AskSocialScience',
 '/r/MillerPlanetside',
 '/r/NFLRoundTable',
 '/r/geospatial',
 '/r/datascienceblogs',
 '/r/math:',
 '/r/statistics:',
 '/r/summonerswar',
 '/r/fantasyfootball',
 '/r/WouldYouRather',
 '/r/Praetkin',
 '/r/Statistics!',
 '/r/scrabble',
 '/r/DeathByCirclejerk',
 '/r/islam',
 '/r/TumblrInAction',
 '/r/SandersForPresident',
 '/r/faq',
 '/r/SAS',
 '/r/askstats',
 '/r/metalcore',
 '/r/popperpigs',
 '/r/DepthHub',
 '/r/epidemiology',
 '/r/databeautiful',
 '/r/dataishorrifying',
 '/r/redditrequest',
 '/r/boardgames',
 '/r/stat',
 '/r/semstatistics',
 '/r/arXiv_Plus',
 '/r/arXiv_Plus!',
 '/r/overdispersion',
 '/r/Android',
 '/r/academiceconomics',
 '/r/todayilearned',
 '/r/P8LP9KM',
 '/r/APStudents',
 '/r/Rstats',
 '/r/publichealth',
 '/r/iamverysmart',
 '/r/woahdude',
 '/r/Mindfulness',
 '/r/TheoreticalStatistics',
 '/r/changemyview',
 '/r/weightroom',
 '/r/DnD',
 '/r/Cubers',
 '/r/2',
 '/r/9Y95PLW',
 '/r/MapPorn',
 '/r/horror',
 '/r/Im15AndThisIsYeet',
 '/r/StudentLoans',
 '/r/BrawlStarsCompetitive',
 '/r/shitpostcrusaders',
 '/r/MLPQHRW?fbclid=IwAR0',
 '/r/MLPQHRW?fbclid=IwAR0_--X5VhKpxVDwRwWO5qVn1yhlCH3vNLX9Stoue66axf_TPdgdCyCaf84',
 '/r/FCInterMilan',
 '/r/ZodiacKiller',
 '/r/Basketball',
 '/r/FootballAmerica',
 '/r/Cricket',
 '/r/hockey',
 '/r/rugbyunion',
 '/r/rugbyleague',
 '/r/baseball',
 '/r/Handball',
 '/r/volleyball',
 '/r/AFL',
 '/r/Bandy',
 '/r/Pesapallo',
 '/r/waterpolo',
 '/r/finance',
 '/r/BmAPog',
 '/r/coolguides',
 '/r/spectralclustering',
 '/r/COVID19',
 '/r/fairness',
 '/r/cscareerquestionsEU',
 '/r/AskStatistics:',
 '/r/ActuaryUK',
 '/r/secretsanta',
 '/r/WatchPeopleDieInside',
 '/r/jav',
 '/r/3d-surface-plots',
 '/r/mycology',
 '/r/blankies',
 '/r/systems_engineering',
 '/r/AskEngineers',
 '/r/HumansBeingBros',
 '/r/law',
 '/r/empirical_bayes_baseball',
 '/r/radicalmentalhealth',
 '/r/chess960',
 '/r/nassimtaleb',
 '/r/optimization',
 '/r/HolUp',
 '/r/aiclass',
 '/r/neurophilosophy',
 '/r/singularitynetwork',
 '/r/transhumanism',
 '/r/pornoverlords',
 '/r/earthporn',
 '/r/fireporn',
 '/r/evolution',
 '/r/casualiama',
 '/r/artificial!',
 '/r/MIT_AI_STUDY_GROUP',
 '/r/samplesize',
 '/r/ludobots',
 '/r/Mneumonese',
 '/r/mashups',
 '/r/concepthut',
 '/r/artifical',
 '/r/WritingPrompts',
 '/r/cybernetics',
 '/r/AskFuturists',
 '/r/ControlProblem',
 '/r/2qjdogz',
 '/r/thatsnotai',
 '/r/magicTCG',
 '/r/startups',
 '/r/startups:',
 '/r/WatchAILearn',
 '/r/worldbuilding',
 '/r/deepfakes',
 '/r/agi',
 '/r/CryptoCurrency',
 '/r/WLYCPDV',
 '/r/bitcoin',
 '/r/VoiceTech',
 '/r/DigitalPhilosophy',
 '/r/blockchain',
 '/r/blockchain_and_ai',
 '/r/software',
 '/r/hardware',
 '/r/AskElectronics',
 '/r/badBIOS',
 '/r/ComputerEngineering',
 '/r/ECE',
 '/r/FPGA',
 '/r/ReverseEngineering',
 '/r/RTLSDR',
 '/r/silicon',
 '/r/V9HMRPD',
 '/r/prettygirls?',
 '/r/dotnet',
 '/r/BasicIncome',
 '/r/homeautomation',
 '/r/PeopleAgainstAGI',
 '/r/Colline',
 '/r/oee',
 '/r/aigents',
 '/r/codes',
 '/r/end',
 '/r/Neurobaby_AGI',
 '/r/3W6FDDS',
 '/r/RASPBERRY',
 '/r/RASPBERRY_PI_PROJECTS',
 '/r/theGPTproject',
 '/r/pics?',
 '/r/RealTesla',
 '/r/Storykube',
 '/r/Fighters',
 '/r/predictor',
 '/r/edtech',
 '/r/EndlessVN',
 '/r/ProjectDecember1982',
 '/r/AIPrompts',
 '/r/mentalhealth',
 '/r/ontology_killer_apps',
 '/r/NaGep4nK1v',
 '/r/MachinesWrite',
 '/r/juststart',
 '/r/PoliticalDiscussion',
 '/r/formula1:',
 '/r/steam[2',
 '/r/Feminism',
 '/r/AdviceAnimals',
 '/r/myweatherstation',
 '/r/askstatistics!',
 '/r/9229L3Z',
 '/r/AskStatistics?',
 '/r/edmproduction',
 '/r/SurveyResearch',
 '/r/AskStatistics!',
 '/r/NFL',
 '/r/Criminology',
 '/r/SWGalaxyOfHeroes',
 '/r/pastorarrested',
 '/r/sas',
 '/r/KotakuInAction',
 '/r/electronic_cigarette',
 '/r/SandersForPresident?',
 '/r/buddhism',
 '/r/custommagic',
 '/r/wow',
 '/r/overwatch',
 '/r/dokumg',
 '/r/Askstatistics',
 '/r/AskProbability',
 '/r/NatureIsFuckingLit',
 '/r/subreddit_stats',
 '/r/Hermitcraft',
 '/r/gamedev:',
 '/r/probabilitytheory',
 '/r/Enough_Sanders_Spam',
 '/r/hardscience',
 '/r/AskPsychology',
 '/r/TK33JHT',
 '/r/AskEconomics',
 '/r/52book',
 '/r/AskAnAustralian',
 '/r/statistics?',
 '/r/AskMath',
 '/r/overclocking',
 '/r/EndFPTP',
 '/r/teenagers',
 '/r/supplychain',
 '/r/empirical',
 '/r/PhdResearch',
 '/r/skeptic',
 '/r/startrek',
 '/r/Conservative',
 '/r/WorldofTanks',
 '/r/OperationExcellence?utm',
 '/r/OperationExcellence?utm_medium=android_app&amp;utm_source=share',
 '/r/mathematics',
 '/r/washingtonNFL',
 '/r/DreamWasTaken2',
 '/r/genetics',
 '/r/probability',
 '/r/auckland',
 '/r/MinecraftCommands',
 '/r/9FHBJWK',
 '/r/AskScienceDiscussion',
 '/r/HDD92R5',
 '/r/PacificCrestTrail',
 '/r/Rstudio',
 '/r/computerscience!',
 '/r/ComputerScience!',
 '/r/Engineering',
 '/r/Dscvry',
 '/r/diycompsci',
 '/r/hosting',
 '/r/webhosting',
 '/r/computerscience?*',
 '/r/AskProgramming',
 '/r/EngineeringStudents',
 '/r/Accounting',
 '/r/2012',
 '/r/computerscuence!',
 '/r/maplesoft',
 '/r/cscareers',
 '/r/unix',
 '/r/AppDevelopment',
 '/r/ireland',
 '/r/breadthfirstgrowth',
 '/r/college',
 '/r/GCSE',
 '/r/T9WHVKQ',
 '/r/MikeAndIke',
 '/r/shittyrobots',
 '/r/programmerhealth',
 '/r/SuggestALaptop',
 '/r/KWW8RSG',
 '/r/MathQuotes',
 '/r/n',
 '/r/HPMagicAwakened',
 '/r/HLXL9CG',
 '/r/helixfoundation',
 '/r/bee',
 '/r/bee_lang',
 '/r/P',
 '/r/P_vs_NP',
 '/r/MathDiscussions',
 '/r/codingplaylists',
 '/r/JTQZCD8',
 '/r/STEM',
 '/r/STEM_Study_Groups',
 '/r/PPGQP57',
 '/r/ProgrammingBuddies',
 '/r/FirstStepsInIT',
 '/r/Office365',
 '/r/OMSCS',
 '/r/androidapps',
 '/r/Happyer',
 '/r/highschoolcompsci',
 '/r/udub',
 '/r/HowToHack',
 '/r/liveoverflow',
 '/r/netsec',
 '/r/learnart',
 '/r/IntegratedCircuits',
 '/r/matheye',
 '/r/WeDivvy',
 '/r/kabooomjs',
 '/r/mildlyinteresting',
 '/r/computervision!',
 '/r/CV',
 '/r/ComputerVision',
 '/r/computervision?',
 '/r/Optics',
 '/r/projecttango',
 '/r/3Dprinting',
 '/r/OCR',
 '/r/ComputerVision!',
 '/r/machinevision',
 '/r/boomapp',
 '/r/Roastme',
 '/r/Libertarian',
 '/r/PHNTM',
 '/r/deaf',
 '/r/THNRN5C',
 '/r/houston',
 '/r/a2d',
 '/r/ruby',
 '/r/DeepLearning',
 '/r/8RM8ZMJ?Channel=pc9bG4',
 '/r/37CW3VP',
 '/r/DataAnalysis',
 '/r/ImageJ',
 '/r/EnoughTrumpSpam',
 '/r/Tableau',
 '/r/vancouver',
 '/r/TheKillers',
 '/r/bestof2020',
 "/r/dataanalysis'",
 '/r/NKG7ghE50V',
 '/r/npoBPw',
 '/r/HYVQZXT',
 '/r/bestof2021',
 '/r/32QR8Y6',
 '/r/WLCYTVZ',
 '/r/jupyter',
 '/r/ETL',
 '/r/S8GT5R8',
 '/r/codingbootcamp',
 '/r/9TZ8BR5',
 '/r/dataengineering!',
 '/r/w5xMN3',
 '/r/stucloud',
 '/r/TheInsaneApp',
 '/r/businessintelligence',
 '/r/personalfinance',
 '/r/MachineLearningJobs',
 '/r/android',
 '/r/data!',
 '/r/conspiracy',
 '/r/Scholar',
 '/r/swipecrypto',
 '/r/restorethefourth',
 '/r/modernwarfare',
 '/r/CanadianInvestor',
 '/r/CBNHXPL',
 '/r/machinlearning',
 '/r/beertrade',
 '/r/learnmanchinelearning',
 '/r/makemychoice',
 '/r/GameUpscale',
 '/r/MLQuestions:',
 '/r/TeamfightTactics',
 '/r/MLquestions!',
 '/r/Lobe',
 '/r/rstats!',
 '/r/rstudio',
 '/r/github',
 '/r/RStats!',
 '/r/rlanguage',
 '/r/rstats?',
 '/r/using-r-in-jupyter-notebooks',
 '/r/dataisbeautiful:',
 '/r/nflstatheads',
 '/r/NLP_TM',
 '/r/regex',
 '/r/line-and-scatter',
 '/r/RExec',
 '/r/session',
 '/r/RStudio',
 '/r/Stats',
 '/r/brasil',
 '/r/all',
 '/r/rshiny',
 '/r/opencpu',
 '/r/RSoftware',
 '/r/3',
 '/r/FIFA',
 '/r/gameofthrones',
 '/r/abudhabi',
 ...]

In [37]:
core.url_extraction(texto)

['http://ad.doubleclick.net/click',
 'http://googleads.g.doubleclick.net/aclk?sa=l&amp',
 'http://www.papajohns.com/index.shtm?utm_source=googlenetwork&amp',
 'http://googleads.g.doubleclick.net',
 'http://i.imgur.com/maV1M.png',
 'http://www.reddit.com/r/stopdrinking',
 'http://www.store.com',
 'https://www.store.yahoo.net',
 'http://imgur.com/d7LbG',
 'http://imgur.com/RIl4s',
 'http://www.escapecreative.com/pdf/google-analytics-sample-report.pdf',
 'http://www.google.com/intl/en/analytics/iq.html',
 'http://www.slideshare.net/dmc500hats/startup-metrics-for-pirates-long-version',
 "https://ssl'",
 "http://www'",
 'http://www.magentocommerce.com/magento-connect/google-universal-analytics-1.html',
 'http://i.imgur.com/pAVvxIq.jpg',
 'http://catbirdanalytics.wordpress.com/2009/01/03/excluding-visitors-from-google-analytics-via-cookie/',
 'http://www.google.com/appsstatus#hl=en',
 'http://hublo.com](http://hublo.com/?utm_source=reddit.com&amp',
 'http://analytics.ncsu.edu/?page_id=123',
 'http://www.mccombs.utexas.edu/Business-Analytics',
 'http://QuickOps.com/contact',
 'http://imgur.com/vkOinWm',
 "https://'",
 "http://'",
 'https://developers.google.com/youtube/analytics/v1/dimsmets/dims#Playback_Location_Dimensions',
 'http://cl.ly/image/2F3G0m3M4300',
 'http://inspiration-point.org',
 'http://www.sisense.com/features',
 'https://support.google.com/analytics/answer/1034840?hl=en',
 'http://i.imgur.com/rhFl36s.jpg',
 'http://i.imgur.com/67SgQbT.jpg',
 'https://userjoy.co',
 'http://www.nmeda.com/locate-a-dealer',
 'http://www.nmeda.com/locate-a-dealer-results/',
 'https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide?csw=1#SettingUpEventTracking',
 'http://www.nmeda.com/locate-a-dealer/',
 'https://productforums.google.com/forum/#!topic/analytics/fKcaFE31SGk',
 'http://tinypic.com/r/15i7sde/8',
 'https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=sv#analyticsjs',
 'https://www.youtube.com/watch?v=O0ErdcmrBis',
 'http://webplio.com.',
 'http://forbes.com/sites/gilpress/2014/10/09/gartner-predicts-top-trends-for-technology-it-organizations-and-consumers-for-2015-and-beyond/',
 'http://mtalavera.wordpress.com/2014/10/21/exploring-cohort-analysis-part-one/',
 'http://www.scottoiler.com/CDA-TO-MP3-CONVERTER-FREE.htm',
 'http://www.scottoiler.com/MOORHUHN-2.htm',
 'http://www.scottoiler.com/TEAIRRA-MARI-SINCERELY-YOURS.htm',
 'http://spdt.co/awN0',
 'https://www.youtube.com/watch?v=wkhpUZg8q-k.',
 'http://www.apointlessfact.com',
 'http://easyanalyticsblog.com/',
 'http://i.imgur.com/JSHFuNs.jpg',
 'http://www.chasinged.com',
 'https://support.google.com/analytics/answer/1034834?hl=en',
 "http://www.mydomain.com'",
 "http://www.mydomain.com/'",
 'http://rekt.gg/.',
 'http://rekt.gg/collections/league-of-legends-tees',
 'http://i.imgur.com/707R4jl.png',
 'https://docs.google.com/document/d/1v04aJk45ThTXaRwFnnWf7kJmD89GJow6hheclpIk2NE/edit?usp=sharing',
 'https://www.surveymonkey.com/s/LKFL9V3',
 'http://imgur.com/a/Wjhzw',
 'http://www.iianalytics.com',
 'http://www.sqlpass.org',
 'http://taveo.net/.',
 'http://imgur.com/AOORjTz',
 'https://express.candarine.com/campaign/url/forward/b19a65629e3b',
 'http://www.reddit.com?cm_mmc=Vendor-_-Category-_-Placement-_-Item&amp',
 'http://sentiment.vivekn.com/',
 'http://tationem.com:8080/TexSIE/',
 'http://puu.sh/fRGg9/203115c677.png',
 'http://www.exampleurl.com',
 'https://developers.google.com/analytics/devguides/collection/upgrade/faq#lose-data',
 'http://imgur.com/nd7NF24',
 'http://www.mollieparksmakeup.com/10-amazing-drugstore-makeup-products/',
 'https://grytics.com/',
 'https://grytics.com/blog/compare-activity-evolution-group-across-time/',
 'http://simplymeasured.com/free-social-media-tools/',
 'http://www.techrepublic.com/article/10-free-analytics-tools-to-help-you-manage-social-media/',
 'http://www.reddit.com/r/analytics/comments/2q9z4c/facebook_usergroup_relationship_analytics/',
 'https://www.facebook.com/help/community/question/?id=10152651460576125',
 'https://www.facebook.com/help/community/question/?id=10100319673559639',
 'http://www.quora.com/Are-there-any-Analytics-solution-for-Facebook-Groups',
 'http://www.steamfeed.com/smartzip-answers-the-real-estate-industrys-call-for-predictive-analytics/',
 'https://www.reddit.com/r/RealEstateTechnology/comments/2zyygq/smartzip_answers_the_real_estate_industrys_call/',
 'https://www.dynamicyield.com/2015/03/personalized-experiences-through-segmentation/',
 'http://www.google-analytics.com/collect?v=1&amp',
 'https://marketing.adobe.com/resources/help/en_US/dtm/load_order.html',
 'http://www.bellinghamaerialmedia.com/',
 'http://www.bellinghamaerialmedia.com/.',
 'http://www.datasciencecentral.com/profiles/blogs/what-technology-tool-skills-do-data-scientists-jobs-require',
 'http://www.researchbeam.com/global-location-analytics-2014-2018-market',
 'http://schulich.yorku.ca/Client/Schulich/Schulich_LP4W_LND_Webstation.nsf/page/MScBA+Program+Length+and+Curriculum?OpenDocument',
 'http://i.imgur.com/BLnvbGi.png',
 'http://en.wikipedia.org/wiki/Basic_income',
 'https://www.dynamicyield.com/ebooks/effective-segmentation/',
 'https://www.youtube.com/watch?v=wwEXxpXsmoE',
 'https://www.crowdanalytix.com/contests/visualization-motorcycle-math',
 'http://i.imgur.com/uDpr92k.png',
 'http://spamscape.net/',
 'https://wordpress.org/plugins/wp-google-analytics-events/',
 'http://i.imgur.com/2HobyPh.png',
 'http://i.imgur.com/1eGvXg3.png',
 'https://UserID:Password@www.domain.com',
 'https://UserID+Password@www.domain.com',
 'https://opserv.io',
 'https://support.google.com/analytics/answer/1032400?hl=en',
 'http://www.simoahava.com/analytics/dont-gtm-listeners-work/',
 'http://www.dailytics.com',
 'http://imgur.com/8sZcYcU',
 'https://www.devtodev.com',
 'https://attendee.gotowebinar.com/register/8590491311326361857',
 'https://attendee.gotowebinar.com/register/1261921956269278466',
 'http://wwp.greenwichmeantime.com',
 'https://www.devtodev.com/promo/blog?id=10061#blogs',
 'http://i.imgur.com/y7Mvd4E.png',
 'https://www.kickstarter.com/projects/313725596/1501626016?token=091a163e',
 'https://www.thinkwithgoogle.com/case-studies/bt-doubleclick-bid-manager-google-analytics.html',
 'https://www.dynamicyield.com/2015/06/data-based-decisions/',
 'https://imgur.com/share/i/8aCAyM8',
 'http://www.reddit.com/r/analytics/comments/39pov4/beating_referral_spam/',
 'http://imgur.com/UvgeYVt',
 'http://stackoverflow.com/questions/30964332/how-to-track-an-event-that-is-defined-using-multiple-variables/30964782.',
 'http://viget.com/advance/removing-referral-spam-from-google-analytics',
 'http://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions',
 'https://blog.kissmetrics.com/5-easy-ga-reports/',
 'https://www.dynamicyield.com/2015/06/dark-social/',
 'https://www.dynamicyield.com/2015/06/dark-social/](https://www.dynamicyield.com/2015/06/dark-social/',
 'http://www.reddit.com/r/socialmedia/comments/37m455/jay_baer_ama_confirmed_june_30th_at_3_pm_et/',
 'http://www.cyfe.com',
 'http://i.imgur.com/3IVX3ol.png',
 'http://i.imgur.com/6J1fK7X.jpg',
 'http://imgur.com/3r5VrXJ',
 'https://code.google.com/p/analytics-issues/issues/detail?id=698',
 'https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filters',
 'http://www.mysite.com/?utm_source=sitename&amp',
 'https://www.youtube.com/watch?v=53C4qgBvL1g',
 'http://imgur.com/a/pEQDv#0',
 'https://mega.nz/#!z51GkQoA!Eh-HNeexputTfUj6JQv9Wg9jx9K6HOzHNh3dfws-pVI',
 'https://www.reddit.com/r/oculus/comments/3degxt/gavr_my_new_app_to_visualize_google_analytics/',
 'http://www.bellevue.edu/degrees/master/business-analytics-ms/',
 'https://www.eventbrite.com/e/analytics-that-excite-2015-tickets-16753897358/?utm_source=Gmail&amp',
 'https://i.imgur.com/JgyzM0t.png',
 'http://gaspamfighter.com',
 'https://www.reddit.com/r/analytics/comments/3exccy/beta_version_of_a_referral_spam_filtering_tool/',
 'https://www.reddit.com/r/SideProject/comments/3e9ui6/referralfiltercom_block_spam_referrals_from/',
 'https://www.referralfilter.com/filter-test',
 'http://i.imgur.com/6YYVWvA.jpg',
 'https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/',
 'http://www.analyticsedge.com/2014/12/removing-referral-spam-google-analytics/',
 'http://mortensondental.com',
 'http://imgur.com/Qcp2kno',
 'http://www.csekcreative.com/blog/news/Sales-and-Marketing/175:busting-strong-ghost-traffic-strong',
 'http://imgur.com/HNtXikV',
 'https://www.conversioner.com/blog/dont-let-your-google-analytics-data-get-polluted-3-things-to-watch?utm_source=Reddit&amp',
 'http://www.seoadsenseguide.com/2015/08/top-5-wordpress-plugins-for-traffic-Monitoring.html',
 'http://www.ryanpraski.com/how-i-found-my-career-in-digital-analytics-on-craigslist-7-years-ago/',
 'https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt',
 'http://getdrip.com',
 'http://www.apple.com/?thankyou=1',
 'http://www.apple.com/thanks/?thankyou=1',
 'https://www.reddit.com/r/exmormon/comments/38wlp9/good_news_for_all_you_masturbators/',
 'https://www.eventbrite.com/e/analytics-that-excite-2015-tickets-16753897358/?utm_source=Reddit&amp',
 'http://www.educationalinstitution.com/offeredprograms/nameofprogram',
 'http://www.educationalinstitution.com/offeredprograms/nameofprogram/howtoapply',
 'http://www.educationalinstitution.com/offeredprograms/nameofprogram/faq',
 'http://www.educationalinstitution.com/offeredprograms/nameofprogram/apply',
 'http://i.imgur.com/qB1kIFz.png',
 'http://imgur.com/45B0afG',
 'http://imgur.com/I0PpJyE',
 'http://i.imgur.com/GXDd0ET.png?1',
 'http://imgur.com/5Q8lyaZ',
 'http://stackoverflow.com/questions/291704/detect-from-browser-if-specific-application-is-installed',
 'https://www.marcozehe.de/2014/02/27/why-screen-reader-detection-on-the-web-is-a-bad-thing/',
 'http://webaim.org/discussion/mail_thread?thread=6326',
 'http://www.nomensa.com/blog/2011/how-do-you-detect-a-screen-reader',
 'http://www.karlgroves.com/2013/05/13/can-we-track-how-many-users-with-disabilities-access-our-site/',
 'http://boxesandarrows.com/the-limitations-of-server-log-files-for-usability-analysis/',
 'https://piwik.pro',
 'https://medium.com/@crowdbabble/crisis-management-101-how-did-digiorno-bounce-back-from-a-cheesy-tweet-e384a8c0839f#.mzjp10c6p',
 'https://referrerspamblocker.com/',
 'https://www.mydomain.com/analytics",',
 'http://www.crowdbabble.com/blog/the-dark-side-how-to-use-google-analytics-to-measure-and-estimate-your-social-media-roi-by-leveraging-dark-social-activity/',
 'https://gist.github.com/anonymous/9cd4910e8402198009a3',
 'http://i.imgur.com/YQCGleA.png',
 'http://www.mintcases.com',
 'http://i.imgur.com/oOYLnTl.png',
 'http://www.brandingidentitydesign.com/',
 'https://www.producthunt.com/tech/charturl',
 'https://charturl.com',
 'https://www.googleapis.com/analytics/v3/management/accounts/~all/webproperties/~all/profiles?start-index=1:',
 'http://imgur.com/a/jIjuO',
 'http://i.imgur.com/S7s6R11.png',
 'http://i.imgur.com/e8uWYI4.png',
 'http://i.imgur.com/Y4mrfUe.png?1',
 'https://network2share.com/',
 'http://richglenoliveoil.com/',
 'http://go.toutapp.com/randomurl123',
 'http://mycompanywebsite.com',
 'http://www.crowdbabble.com/blog/facebook-analytics-101-like-sources/',
 'https://support.google.com/analytics/answer/2795983?hl=en',
 'http://simoahava.com/analytics/send-weather-data-to-google-analytics-in-gtm-v2/',
 'http://www.hoverowl.com.',
 'https://www.google.com/analytics/web/?hl=en&amp',
 'http://webcache.googleusercontent.com/search?q=cache:bdKCclwK6lcJ:https://yoast.com/wordpress-robots-txt-example/&amp',
 'https://www.reddit.com/r/PPC/comments/3xkvdf/adwords_custom_report_in_google_analytics/',
 'http://www.analyticscanvas.com/uncover-conversion-funnels/',
 'http://prntscr.com/9n2468',
 'http://imgur.com/47TXCqi',
 'http://imgur.com/dvKQUBv',
 'http://imgur.com/lKMdbEw',
 'http://referral-spam-killer.metrics.watch/',
 'http://i.imgur.com/0eTZphZ.jpg',
 'http://dot.fm/2015Top100.pdf',
 'http://how.to.travel.and.make.money.online.for.free.with.maps.ilovevitaly.com/',
 'http://domainname.com/?utm_campaign=CampaignName&amp',
 'http://prntscr.com/a1zkz0',
 'https://i.imgur.com/ONJxVyx.png](https://i.imgur.com/ONJxVyx.png',
 'https://support.google.com/analytics/answer/3198398?hl=en',
 'http://www.confluentforms.com/2016/02/aligning-buyer-personas-content-analytics.html',
 'http://imgur.com/j7Yw9YD',
 'https://support.google.com/analytics/answer/2568878?hl=en',
 'https://segment.com/blog/chief-data-officer/',
 'http://www.simoahava.com/spamfilter/',
 'http://tagmanageable.com/',
 'http://vanityurl.com,',
 'http://vanityurl.com.',
 'http://marketing.happymarketer.com/ace-your-marketing-strategy-with-14-types-of-data',
 'http://www.kwalert.net/',
 'http://productforums.google.com/d/topic/analytics/?',
 'http://i.imgur.com/KKeUPct.png',
 'https://www.en.advertisercommunity.com/t5/Google-Analytics/ct-p/Google_Analytics',
 'http://webcache.googleusercontent.com/search?q=cache:pM7kCI5j3psJ:productforums.google.com/d/topic/analytics/5yc5_8kR_oc+&amp',
 'http://i.imgur.com/HVbhsBl.png',
 'https://www.reddit.com/r/webdev/comments/1ok2o8/why_my_reddit_ad_traffic_clicks_and_google/',
 'http://independentbostonhotels.com/',
 'http://marketingland.com/time-cut-cord-traditional-web-analytics-four-questions-ask-167901',
 'http://www.justbecause-xoxo.com/',
 'https://duracelltomi.com/google-tag-manager-for-wordpress',
 'http://imgur.com/Qzwdktc',
 'https://www.onehopeunited.org',
 'https://www.denexa.com',
 'http://imgur.com/HQmr6bp',
 'http://i.imgur.com/FH92UXO.png?1',
 'http://metricswatch.com/what-is-referral-spam-and-how-to-prevent-it-in-less-than-5-minutes/',
 'http://i.imgur.com/dvLsosq.png',
 'http://www.pagewiz.com/blog/conversion-rate-optimization/10-12-cro-mistakes-and-what-we-can-learn-from-them',
 'http://www.bentley.edu/graduate/ms-programs/business-analytics',
 'http://science.iit.edu/programs/graduate/master-data-science',
 'http://www.simon.rochester.edu/programs/full-time-ms/academics/programs/business-analytics/index.aspx',
 'http://www.analytics.gatech.edu/',
 'http://www.soic.indiana.edu/graduate/degrees/data-science/ms-data-science/',
 'https://support.google.com/analytics/answer/2695658?hl=en',
 'https://d262ilb51hltx0.cloudfront.net/max/600/1*ye34AeYa-DUQIRDN8fSGNw.png',
 'https://d262ilb51hltx0.cloudfront.net/max/800/1*wrMez1isCuK5TcErXsRrXg.png',
 'https://d262ilb51hltx0.cloudfront.net/max/800/1*TnoJJWA-g2BVCg-vdylQuQ.png',
 'https://d262ilb51hltx0.cloudfront.net/max/800/1*aP6EsvxmrbqDJd14tsRYjg.png',
 'http://digitalmarketing.ctp.com/hs-fs/hubfs/Blog/Images/User_Explorer_Report_-_Scroll_Down.png?t=1460546196975&amp',
 'https://simplr.tibco.com',
 'https://ga-dev-tools.appspot.com/query-explorer/#report-end',
 'https://segment.com/',
 'http://i.imgur.com/91sn32Q.jpg?fb',
 'https://developers.google.com/analytics/devguides/reporting/core/v4/',
 'http://i.imgur.com/as0LfxU.png',
 'http://analyticshour.libsyn.com/035-is-data-science-the-future-of-web-analytics',
 'http://www.verticalrail.com/kb/filter-in-google-analytics-to-track-subdomains/',
 'http://www.matthewwoodward.co.uk/tutorials/how-to-track-anything-with-google-analytics/',
 'https://www.hhhsupply.com]',
 'http://popcontent.co.uk/2016/04/29/google-search-console-integration-how-to-content-marketing/',
 'https://newrst.wordpress.com/',
 'https://www.reddit.com/r/PPC/comments/4fs9gq/how_to_provefalsify_weekend_traffic_hypothesis/',
 'https://www.youtube.com/watch?v=eTRxUaViJno',
 'https://www.reddit.com/r/webdev/comments/3fx9du/most_of_your_traffic_isnt_real_try_this_google/',
 'https://moz.com/blog/stop-ghost-spam-in-google-analytics-with-one-filter',
 'http://i.imgur.com/TFQq7Q4.png',
 'https://www.themarketingtechnologist.co/having-fun-with-google-analytcis-cross-device/.',
 'https://services.google.com/fb/forms/gps-livestream/',
 'http://colorbrewer2.org/',
 'http://i.imgur.com/XmIyxgE.png',
 'http://i.imgur.com/jEM7G5h.png',
 'http://imgur.com/a/yx6Tl',
 'http://imgur.com/HsQfQZY',
 'https://github.com/blast-analytics-marketing/sql-recipes/blob/master/google-analytics-clickstream-data-bigquery-export.sql',
 'https://support.google.com/analytics/answer/2709828?hl=en',
 'https://clickhouse.yandex/',
 'https://clickhouse.yandex/benchmark.html#[100000000,["ClickHouse","Vertica","InfiniDB","MonetDB","Hive"],["0","1"]]',
 'https://clickhouse.yandex/reference_en.html',
 'http://www.conversion-rate-services.com/blog/2011/november-2011/using-custom-variables-to-track-registered-users-i/',
 'http://imgur.com/txt4mQL',
 'https://myblogonbloggerblahblah.blogspot.com/search/label/bicycle',
 'http://imgur.com/sQYJpMy',
 'http://www.zineomatic.com//zine-o-matic/',
 'http://imgur.com/XjbnokU',
 'http://www.abovemba.com/pages/entrepreneurship?utm_source=twitterMBAU&amp',
 'http://supermetrics.com/blog/#!segment-google-analytics',
 'http://imgur.com/8zcMobL',
 'http://imgur.com/FTavUDN',
 'https://recruit.zoho.com/recruit/ViewJob.na?digest=.fzPxKohrdZz1R4P@6DSGme12KljcJKLJArrDUyv15U-&amp',
 'https://github.com/Nastel/jkool-rum-plugin',
 'https://www.jkoolcloud.com',
 'http://www.degordian.com/education/blog/tracking-pdf-downloads-as-pageviews-using-google-tag-manager-v2/',
 'https://fs20.formsite.com/res/showOrderReview?EParam=m%2FOmK8apOTCXVt5BgY3ZIn5%2FpBxO5FCh2CO%2BcxzjbeqqSMZRZXlnpsqGxZMgg9l%2F%2FArK4DFZ9xfa%2FXpLNif2pA%3D%3D',
 'http://help.fullstory.com/integrate-ref/ga_universal',
 'https://i.imgur.com/y5pAVII.jpg',
 'http://imgur.com/wdZF2sK',
 'http://imgur.com/a/oWYLT',
 'http://i.imgur.com/3vCZIPQ.png',
 'https://databox.com/product',
 'https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4',
 'http://docs.sequelizejs.com/en/latest/',
 'http://www.highcharts.com',
 'https://developers.google.com/analytics/devguides/reporting/core/v4/rest/',
 'http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/',
 'http://imgur.com/a/0ziMh',
 'http://imgur.com/a/NoHzK',
 'http://i.imgur.com/ymAJqvg.jpg',
 'http://i.imgur.com/ogF5Pw7.jpg',
 'http://i.imgur.com/vauCWxu.jpg',
 'https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#sampleRate',
 'http://i.imgur.com/GC9ZdN7.png',
 'http://imgur.com/Egrdevo',
 'http://imgur.com/GcZPhTs',
 'http://imgur.com/1qy95g4',
 'http://imgur.com/a/cQGco',
 'http://imgur.com/a/ZT1fD',
 'https://developers.google.com/analytics/devguides/reporting/embed/v1/getting-started]',
 'https://datastudio.google.com/',
 'https://cse.google.com/cse/all',
 'http://www.mycoachonline.com',
 'https://www.google.com/analytics/terms/us.html',
 'http://www.danielpinero.com/how-to-see-ip-address-google-analytics',
 'https://support.google.com/analytics/answer/3297892?hl=en',
 'http://imgur.com/a/EdaIV',
 'https://schema.org/WebSite',
 'https://schema.org/Organization',
 'https://schema.org/owns',
 'https://schema.org/Product',
 'https://',
 'https://github.com/JamesFX2/PO-Analytics/blob/master/core.js',
 'http://i.imgur.com/Ph8WtZ7.png',
 'https://github.com/FrankPortman/bayesAB',
 'https://cran.r-project.org/web/packages/bayesAB/vignettes/introduction.html',
 'http://webmasters.stackexchange.com/questions/58516/does-service-provider-dimension-correspond-to-isp-organization-filter-in-ana',
 'http://audiencestack.com/static/images/analytics-exclusion.jpg',
 'https://imgur.com/a/vMkLl',
 'http://i.imgur.com/Bfln3AY.png',
 'http://imgur.com/db9aa28c-bef5-4c2a-a0f8-a8d9fb702b89',
 'https://support.google.com/analytics/answer/1012243?hl=en',
 'https://www.quillengage.com/',
 'https://www.jackthreads.com/?utm_source=members&amp',
 'https://developers.google.com/analytics/',
 'http://example.com/page1',
 'http://example.com/page3',
 'http://stackoverflow.com/questions/38392173/getting-audience-user-explorer-details-from-google-analytics-using-api-what-wil',
 'https://www.mysite.com,',
 'https://app.mysite.com,',
 "https://www.google-analytics.com/analytics.js','ga'",

In [38]:
core.phone_number_extracion(texto)

['919-404-9233',
 '593-019-0517',
 '586-020-2649',
 '256-020-0023',
 '586-020-0307',
 '537-020-0039',
 '467-021-2395',
 '586-021-0381',
 '467-021-2522',
 '537-019-0197',
 '598-021-9396',
 '592-021-0125',
 '586-021-0425',
 '521-022-0688',
 '333-333-3333',
 '640-018-0316',
 '256-019-0088',
 '916-019-1466',
 '537-019-0282',
 '804-627-9544',
 '565-021-0087',
 '467-020-1728',
 '222-019-0991',
 '537-019-0186',
 '917-727-7959',
 '801-328-2077',
 '597-019-0247',
 '859-015-0564',
 '168-018-0417',
 '597-021-0093',
 '423-015-0890',
 '524-020-0307',
 '142-017-9407',
 '598-019-4776',
 '263-015-0872',
 '598-021-8159',
 '598-020-7914',
 '586-021-0263',
 '586-021-0385',
 '559-020-0976',
 '593-019-0460',
 '047-006-9026',
 '479-006-0131',
 '266-786-1017',
 '618-014-0377',
 '489-017-0999',
 '586-018-0603',
 '592-018-0109',
 '591-018-0177',
 '586-018-0711',
 '598-018-3481',
 '994-018-5742',
 '586-019-0008',
 '256-018-0002',
 '591-018-0335',
 '206-701-6702',
 '374-019-0202',
 '586-019-1119',
 '586-019-0132',
 '034-002-2007',
 '592-018-0229',
 '586-018-0438',
 '591-019-0539',
 '587-019-0224',
 '586-019-1582',
 '593-019-0520',
 '452-019-1044',
 '748-019-0020',
 '256-019-0104',
 '467-019-1313',
 '586-019-0389',
 '586-019-1799',
 '586-020-0027',
 '115-013-0658',
 '586-020-0001',
 '592-019-0500',
 '598-018-2361',
 '256-020-0161',
 '583-020-0277',
 '864-019-6413',
 '467-020-1587',
 '544-019-0390',
 '586-019-0221',
 '586-020-0091',
 '256-019-0048',
 '467-020-1726',
 '467-020-1751',
 '598-019-5618',
 '586-020-2939',
 '467-020-1836',
 '888-785-8272',
 '586-020-0305',
 '586-019-1923',
 '598-020-7931',
 '994-013-5379',
 '586-021-0322',
 '586-020-0315',
 '072-128-3072',
 '467-021-2176',
 '256-021-0031',
 '676-021-0958',
 '256-021-0030',
 '598-021-8481',
 '598-021-8701',
 '598-021-8911',
 '146-020-0104',
 '467-020-0000',
 '636-017-0123',
 '537-020-0031',
 '435-021-0014',
 '467-021-2426',
 '598-021-9374',
 '263-019-0119',
 '586-021-0382',
 '586-021-0213',
 '598-021-8254',
 '598-019-4561',
 '467-021-2580',
 '593-021-0085',
 '592-021-0124',
 '256-021-0040',
 '458-021-0951',
 '428-019-0121',
 '978-966-2094',
 '978-966-9663',
 '844-021-0068',
 '586-021-0358',
 '562-021-0114',
 '081-017-9366',
 '586-021-0408',
 '256-021-0043',
 '586-022-0444',
 '586-021-0430',
 '894-020-0025',
 '003-022-0303',
 '911-020-0123',
 '222-006-9006',
 '268-005-0035',
 '423-015-0947',
 '562-017-0189',
 '539-018-0028',
 '586-018-0566',
 '806-016-0048',
 '749-010-0189',
 '586-019-0224',
 '598-019-5444',
 '874-019-0829',
 '654-016-0149',
 '567-020-0921',
 '586-020-0334',
 '551-020-0064',
 '428-018-1060',
 '428-017-0976',
 '229-021-0327',
 '586-020-0067',
 '586-018-0747',
 '477-020-0179',
 '874-021-0131',
 '874-020-0110',
 '423-021-0193',
 '746-020-0224',
 '662-016-0789',
 '586-018-0614',
 '146-019-0087',
 '586-019-1138',
 '256-019-0036',
 '540-019-0086',
 '586-019-1666',
 '586-020-2735',
 '599-020-0067',
 '524-021-0053',
 '928-021-0061',
 '467-021-2333',
 '398-021-0149',
 '586-019-0168',
 '557-021-0076',
 '467-021-2534',
 '587-021-0100',
 '598-021-9437',
 '591-021-0150',
 '380-021-0131',
 '467-021-2675',
 '256-020-0219',
 '467-021-2760',
 '598-021-0357',
 '586-021-0422',
 '467-022-2853',
 '587-021-0117',
 '259-002-0869',
 '038-017-1018',
 '392-013-0642',
 '806-018-0152',
 '889-019-7094',
 '428-012-0196',
 '874-017-0322',
 '586-019-0085',
 '064-015-0220',
 '060-017-0045',
 '205-013-0480',
 '192-018-3724',
 '970-014-0064',
 '406-009-0015',
 '423-016-1015',
 '258-006-9126',
 '598-020-7706',
 '747-007-0077',
 '203-021-0031',
 '586-021-0349',
 '692-021-0019',
 '181-020-0197',
 '295-020-0022',
 '400-188-1999',
 '408-956-6440',
 '925-826-2902',
 '263-017-0999',
 '866-923-5805',
 '537-019-0192',
 '467-021-2656',
 '586-021-0426',
 '480-555-1234',
 '626-921-4904',
 '598-019-4530',
 '874-016-0200',
 '748-016-0094',
 '670-009-9199',
 '746-018-0029',
 '537-017-0083',
 '321-020-0414',
 '467-021-2133',
 '256-020-0180',
 '122-012-1960',
 '531-008-0312',
 '421-020-0434',
 '428-013-0424',
 '874-015-0022',
 '859-021-0410',
 '444-444-4444',
 '555-555-5555',
 '844-385-6929',
 '832-508-0431']

In [39]:
core.dates_extraction(texto)

['01/01/2021',
 '10/30/1011',
 '02/06/8449',
 '12/17/2020',
 '18/12/2020',
 '12/22/2020',
 '12/23/2020',
 '12/25/2020',
 '12/30/2020',
 '12/31/2020',
 '01/01/2020',
 '16/10/3988',
 '07/21/1029',
 '02/23/1044',
 '01/31/2013',
 '14/01/1432',
 '11/12/2013',
 '01/01/2017',
 '02/01/2017',
 '03/01/2017',
 '06/30/2017',
 '17/01/1517',
 '18/03/2218',
 '09/26/6518',
 '01/30/2019',
 '01/20/2019',
 '19/07/2019',
 '10/13/5253',
 '10/29/1532',
 '03/07/2020',
 '10/31/2019',
 '11/25/2019',
 '14/09/2020',
 '26/09/2020',
 '28/09/2020',
 '02/02/2020',
 '20/02/2020',
 '06/14/8765',
 '01/18/9579',
 '31/03/2020',
 '30/06/2020',
 '30/09/2020',
 '16/14/6732',
 '10/26/7341',
 '11/23/2000',
 '17/48/3009',
 '13/10/3596',
 '08/02/2019',
 '13/21/4486',
 '04/02/1097',
 '11/43/1532',
 '10/02/1309',
 '01/40/1433',
 '05/11/2015',
 '02/12/2015',
 '09/14/1973',
 '01/01/1979',
 '01/02/2014',
 '17/05/1961',
 '10/09/2018',
 '12/27/2018',
 '03/06/2014',
 '03/05/2019',
 '03/05/6969',
 '12/02/2018',
 '07/15/1969',
 '09/11/2001',
 '03/23/2016',
 '18/10/1111',
 '98/20/1146',
 '09/12/5050',
 '11/25/2017',
 '15/03/2020',
 '05/07/1000',
 '11/17/2020',
 '10/25/2007',
 '19/03/9466',
 '20/04/2020',
 '14/02/2014',
 '02/21/2016',
 '08/17/2016',
 '08/21/2016',
 '06/19/0597',
 '04/23/0001',
 '05/09/2017',
 '12/03/2019',
 '12/04/2019',
 '12/05/2019',
 '02/03/2014',
 '08/02/2016',
 '10/02/2020',
 '20/10/2010',
 '16/52/2715',
 '11/12/2020',
 '05/30/2020',
 '10/27/1036',
 '05/05/2021',
 '05/18/2021',
 '01/02/2021',
 '01/03/2021',
 '02/10/2021',
 '02/11/2021',
 '26/08/2018',
 '26/03/2004',
 '02/06/2003',
 '20/05/2022',
 '26/08/2020',
 '12/23/3888',
 '15/23/5849',
 '10/09/1009',
 '03/01/1166',
 '03/01/2016',
 '02/09/1513',
 '12/17/1037',
 '14/02/2410',
 '16/01/1432',
 '09/20/2016',
 '11/29/2016',
 '16/11/1611',
 '03/13/1611',
 '14/13/3521',
 '17/12/6270',
 '12/30/2403',
 '18/07/2018',
 '10/03/1975',
 '04/13/2959',
 '03/27/1820',
 '12/31/2018',
 '16/16/7723',
 '29/05/2019',
 '04/28/6208',
 '02/28/1800',
 '06/09/2017',
 '08/27/2019',
 '19/11/1321',
 '11/02/2003',
 '16/01/1830',
 '06/24/8826',
 '07/06/1004',
 '05/27/1328',
 '08/13/1907',
 '08/22/1007',
 '08/13/1006',
 '08/18/1007',
 '09/04/1008',
 '20/09/2009',
 '09/09/2091',
 '09/17/1008',
 '09/14/1008',
 '17/43/2656',
 '11/18/1012',
 '12/04/1013',
 '12/03/2139',
 '12/07/9440',
 '12/08/2020',
 '14/50/1310',
 '02/22/0434',
 '07/20/1005',
 '10/08/1009',
 '06/08/2243',
 '21/07/4209',
 '12/10/1013',
 '33/22/3575',
 '10/10/2021',
 '10/19/2021',
 '03/02/2022',
 '11/22/1075',
 '13/15/3932',
 '12/31/2021',
 '12/29/1043',
 '02/16/1045',
 '20/16/4603',
 '13/19/3834',
 '71/18/1625',
 '10/25/1150',
 '19/08/2014',
 '04/13/3994',
 '02/21/2015',
 '08/17/2015',
 '12/25/7629',
 '11/01/2016',
 '01/01/1997',
 '31/12/2017',
 '13/07/2019',
 '13/07/2003',
 '14/07/2019',
 '14/07/2010',
 '08/11/6374',
 '01/05/1948',
 '14/04/1965',
 '11/12/1962',
 '09/11/1989',
 '16/10/4176',
 '23/12/2010',
 '15/11/2600',
 '69/11/1856',
 '05/14/8553',
 '12/01/2137',
 '08/28/7551',
 '04/07/5380',
 '22/12/1435',
 '13/10/1112',
 '13/05/8676',
 '11/25/7276',
 '20/10/5234',
 '07/24/1541',
 '07/26/1542',
 '07/23/1540',
 '07/27/1543',
 '07/24/1540',
 '07/27/4962',
 '07/25/1541',
 '12/06/2019',
 '10/26/2093',
 '10/25/2093',
 '11/11/2020',
 '12/14/2352',
 '17/12/2703',
 '09/01/0103',
 '03/24/3949',
 '12/31/2015',
 '01/01/2010',
 '05/01/2012',
 '08/01/2012',
 '28/10/2723',
 '05/12/5280',
 '03/03/2017',
 '03/04/2017',
 '33/17/2768',
 '14/35/0914',
 '08/10/2018',
 '08/12/2018',
 '08/14/2018',
 '08/02/2018',
 '08/08/2018',
 '02/09/2019',
 '03/09/2019',
 '01/01/1900',
 '21/01/1900',
 '24/12/2019',
 '16/32/1587',
 '17/16/9127',
 '39/39/7748',
 '31/12/2020',
 '01/09/2021',
 '02/09/2021',
 '03/09/2021',
 '04/09/2021',
 '05/09/2021',
 '06/09/2021',
 '15/29/7521',
 '12/06/2021',
 '08/22/1029',
 '15/04/2017',
 '16/04/2017',
 '02/17/1510',
 '37/11/2895',
 '08/05/1006',
 '11/26/2020',
 '25/03/2021',
 '29/03/2021',
 '12/13/1901',
 '10/11/4321',
 '10/11/1827',
 '18/03/2666',
 '12/12/2002',
 '09/01/2021',
 '20/12/3387',
 '01/01/2008',
 '03/03/2008',
 '06/06/2010',
 '04/12/2017',
 '23/12/2020',
 '08/22/2021',
 '12/31/2019',
 '01/07/2021',
 '01/08/2021',
 '01/14/2021',
 '01/22/2022',
 '03/31/2020',
 '10/11/2019',
 '11/25/2171',
 '03/02/1993',
 '12/31/1970',
 '20/09/2020',
 '01/24/2021',
 '07/30/2021',
 '15/12/2021',
 '19/01/2022',
 '15/01/1841',
 '01/04/2019',
 '01/09/2020',
 '29/04/2021',
 '03/08/2015',
 '29/07/2015',
 '28/07/2015',
 '19/03/2015',
 '10/23/1943',
 '24/04/2015',
 '11/12/2009',
 '30/07/2015',
 '09/08/2015',
 '14/05/2014',
 '21/03/2017',
 '28/03/2017',
 '05/07/2017',
 '20/10/2017',
 '12/14/2018',
 '01/09/2014',
 '04/13/2015',
 '07/11/2015',
 '10/12/2015',
 '09/30/2015',
 '03/12/2016',
 '03/14/2016',
 '11/10/2015',
 '04/17/2011',
 '06/12/2013',
 '09/04/2011',
 '04/22/2012',
 '10/24/2012',
 '05/11/2014',
 '03/25/1206',
 '12/01/2008',
 '10/20/2017',
 '01/01/2018',
 '01/01/2043',
 '01/05/1990',
 '05/05/1995',
 '11/13/2000',
 '09/10/2010',
 '12/30/2014',
 '07/19/2015',
 '10/16/2018',
 '12/01/2018',
 '23/09/2005',
 '05/07/2019',
 '15/06/2013',
 '01/12/2019',
 '02/22/2019',
 '01/07/2016',
 '30/06/2017',
 '01/10/2016',
 '01/02/2017',
 '30/09/2016',
 '31/01/2017',
 '01/01/2003',
 '01/01/2004',
 '10/25/2019',
 '24/11/2017',
 '14/03/2020',
 '31/12/2019',
 '20/03/2020',
 '12/20/2019',
 '12/29/2019',
 '12/30/2019',
 '12/29/2020',
 '03/03/2020',
 '10/10/2020',
 '12/21/2020',
 '04/01/2019',
 '11/29/2020',
 '06/03/2021',
 '10/16/2009',
 '11/11/2021',
 '10/10/2010']

In [40]:
core.code_extraction(texto)

[<NA>,
 'window.dataLayer = window.dataLayer || [];',
 'from tensorflow.python.client import device_lib',
 "Hello fellow learners. I came up with a deep learning project idea. It involves images as well as regular attributes and classifies (height, weight, name). The problem I came across is how do I combine this two different universes together in a meaningful way. I did some research and I found this idea of multimodal learning. Modalities refer to the different dimensions of perception. For humans it would be smell vision and so on. In all the research done so far the best approach I could find was building 2 NN's to do separate tasks and then combine them with another smaller NN that would adjust its weighted contribution. There are problems in this approach. ",
 "Hi, I'm currently a data scientist working in finance and I'm curious about what kind of opportunities will be available to me in the future if I decide to stay in finance instead of tech or vice versa. ",
 'df = df.resample("D", how="mean")',
 'Thanks for clicking in. ',
 'import shutil',
 'urgency = ["asap", "now", "quickly"] test = \'the patientneeds help/asap\' if any(elem in test.split() for elem in urgency): print(\'Element Found\')',
 'Hi guys, I cleared the entry level Google PhD data scientist screening round and need suggestions on what to prepare. I guess there will be 5 rounds + 1 "Googlyness" behavioral round. I read some posts in this thread but was hoping to avail some more recent advice.',
 'import numpy as np',
 "p_issue = Label(top, text='ISSUE DATE', font=('bold', 10))",
 "I'm working on the project of economics under the topic of data analytics, in which i have to get data for analysis.I'm confused how can i proceed further without data sets and data analysis. I've checked it from lots of sites. I got one IEEE research paper and one article regarding this. In that there is much better explanation and good data also but that data is their data and i can't take that data in my own project because if you are working for your own project then you are supposed to get  that data for your own and do analysis and then make literature review on this.",
 'from __future__ import absolute_import',
 'function [J, grad] = costFunction(theta, X, y)',
 '[U,S,V] = svd(A);',
 'import os',
 'E:\\python\\Twitter-Sentiment-Analysis&gt;python main.py',
 'from sklearn import datasets',
 'RuntimeError: simple_bind error. Arguments:',
 'def data_generator():',
 'from tensorflow.keras.layers import *',
 'model = keras.Sequential([Dense(...), BatchNormalization(...), Activation(...)])',
 'nn = Sequential([Dense(10, input_shape=(shape of x without batch size), BatchNormalization()]',
 'import gym',
 'pipe = Pipeline([',
 "parameters['W' + str(l)] = np.zeros((layers_dims[l], layers_dims[l-1]))",
 'class rotation_kernel(nn.Module):',
 'delta = np.dot(self.layers[-i + 1].weights.transpose(), delta) * sigmoid.derivative(zs[i])',
 'def replay(self, batch_size):',
 'def check_state_has_winner(nn_state, who_is_playing):',
 'self.model.fit(state, target_f,batch_size=512, epochs=20, verbose=0)',
 'a_C_unrolled = tf.reshape(a_C, [-1]) ',
 'const is = require(‘is-thirteen’);',
 'train_datagen = ImageDataGenerator(',
 '#The sigmoid function',
 '# preprocessing the data',
 'with tf.variable_scope("name"):',
 'import torch',
 'MAKE_TRAINING_TESTING_DATA = False',
 'import tensorflow as tf',
 'class Net(nn.Module):',
 'EPOCHS = 5',
 'function [J, grad] = lcostf (Theta, X, Y)',
 'findClosestCentroids.m ',
 'from sklearn.metrics import roc_auc_score',
 'oecd_bli = pd.read_csv("oecd_bli_2015.csv", thousands=\',\')',
 'np.array(keras.utils.to_categorical(y_train, numClasses))',
 'x = [6429, 3099, 6267, 6445, 5594, 5881, 6179, 4832, 3913, 6422]',
 'arma::mat data(3, inImage-&gt;w * inImage-&gt;h)',
 'train=timeseries_dataset_from_array(',
 '#linear regression',
 'def cost(i,o,w):',
 'loss_fn = nn.CrossEntropyLoss()',
 "data = np.loadtxt('data.txt', dtype = str)",
 "I have just finished Andrew Ng's Linear regression exercise and decided to do one example by taking data from GitHub on my own. I am not getting the correct output in my linear regression using gradient descent. Any help to rectify this error would be appreciated",
 '#Code for pickle',
 'mport numpy',
 '# Python dictionary to act as an adjacency list',
 'import numpy as np ',
 '#Tuning parameters',
 'tweets = []',
 '#This function converts to lower-case, removes square bracket, removes numbers and punctuation from test data',
 'model = Sequential()',
 'neuralnet: chanceB = 1/(1+e^-sum&lt;i&gt;(weightBC*chanceC))',
 '^',
 'X_train, X_test, y_train, y_test = train_test_split(training.data,training.predictions,train_size=0.6)',
 '```',
 'User_id, review ',
 'Stable Neural Flows',
 'w = np.random.randn(n) * sqrt(2.0/n)    ',
 'using System.Collections;',
 '# image specification ',
 'chubakbidpaa.com/cbgen (Colab Gist)',
 '&gt; myloop',
 'Let S={x1, x2, x3, xn}',
 'Affirmed Number Previous_Affirmed',
 'I have to run a two-way ANOVA on a data set, but my dependant variable (participants were asked how attractive someone is on a scale of 1-10 three different times) was entered into SPSS as three different dependant variables. ',
 "if we have a list like [15,15,15,15,15,15,15,15,15,14,14,14,14,14,13,13,13,13,12,12,12,12,12,12,12] so this list contain 4 type of digits (15*9/14*5/13*4/12*7) let's say we want to divide these digits on 5 persons in a way the sum of digits in the hands of everyone is 68 or 69 (the sum of these terms divided by the number of persons is 68.2)",
 'x &lt;- seq(-3, 3, by=0.1)',
 'Hello, I’m planning on either doing Finance or Accounting and would like to add either Stat or Data Science as a second major. My question is what are the differences and which would you recommend? Also, is Finance and Stat or Data Science employable? (I’m currently attending SMU in Dallas if this matters).',
 'Part 1: Calculating J without  Regularization ',
 'I have a debate coming up next week and I need help with some talking points, arguments, or theories that could be used to argue why A.I. is bad. Also is there any alternatives to A.I.?',
 'I have started a reddit community to discuss ideas and architectures for designing applications that make use of ontologies, particularly those based in some form of description logics.  ',
 'Confusion Matrix and Statistics',
 "Doing a meta-analysis the first time in my life, so any advice will be appreciated. I'm interested in comparing the official safety profile (from 1 big phase 3 study) of a recently approved chemo drug to see it matches up with other smaller studies done around the same time (about 10 other phase 1 and 2 studies, none has control groups, only the same drug). The main measurement would be odds ratio, specifically to see if a side effect % from the big phase 3 study would also be seen in the 10 other smaller studies. ",
 'Data Sets',
 'A research article reports the results of a new drug test. The drug is to be used to decrease vision loss in people with Macular Degeneration. The article gives a p-value of .04 in the analysis section',
 '&gt; set.seed(1)',
 'L1*B1*F1 + L2*B2*F2 + L3*B3*F3 = 2500',
 'Hello, tell me, please - Am I finding the root-mean-square error correctly?',
 'private static int f(int[] a, int low, int high)',
 'int recursiveCensorTail(int p, int n) {',
 '0. Supplementary to logic\t\t\t      : Logicomix',
 'void fft2InPlace(complex *c, unsigned int n)',
 "&lt;numerals&gt; ::= '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'",
 'number=0',
 "Hey all. I managed to get my hands on a couple of surveillance hard drives and was curious as to if I could use them for storage in a PC. The model is WD20PURZ. I don't see why I wouldn't be able to but I'm quite the noob when it comes to computers so if anybody has any insight on this please share! Thanks. =)",
 'def shift(board, d = 1):',
 'i = 10',
 'done = True',
 '#Retrieves input from user in integer form',
 '#include &lt;iostream&gt;',
 'allChr = []',
 'x = 1 ------ 1',
 '#include &lt;stdio.h&gt;',
 'def f(n):',
 "specifiedItem = 'item6'",
 'if (first_loop):',
 'import cv2',
 'cv::Mat yuvImg; ',
 '##############################',
 'for(int i=0;i&lt;imgB.cols*imgB.rows;i++){',
 'class Test',
 'x = df["building_genre"]',
 'Tell me about your job if you feel like youre helping people and making positive changes!! :)',
 'SELECT product3       AS product',
 '# my code ',
 'Given the table: Bonuses',
 'This database is used to be able to persist train stations. A train-',
 'The database returned the following error:',
 'Rondo kempling pancen puenak.....??!!',
 'Bolongan apa tah sing isa ngemut, ya kuwi sing di arani tutuk',
 'Rondo kempling pancen puenak.....??!! opo maneh rondo teles. . . haduch haduch ora kuat mikir cak. .. ..ώκώκ˚•♧•˚ώκώЌώ……',
 'Gunung kelud,gunung batu,Nu teu boga udud,osok memelas bari ngarayu,Gunung kelud,gunung batu,Nu teu boga udud,osok memelas bari ngarayu,Gunung kelud,gunung batu,Nu teu boga udud,osok memelas bari ngarayu',
 'Assolole',
 '[^BapHet^] Watch Pixels Online.. Free Stream Full.. Movie HD..Watch Pixels Online Free | Pixels SeWatch Pixels -- | Watch Pixels Online Free Megashare | Watch Pixels Online Free Putlocker | Watch Pixels Online Free Viooz |1st-movie watch Pixels online 2015 full free | Action ... 1 day ago - Watch Pixels Online Free, Watch Pixels 2015 English Full Movie, Watch Pixels 2015 Full Movie Free Streaming Online with English Subtitles ... [[FULL-HD]] WATCH Pixels ONLINE FREE (2015) | Action ... 1 day ago - [Mega-Film] Pixels” Full Online M.O.V.I.E Free.Pixels is amazing, Upcoming movie to watch. Watch Pixels..Full Movie..Online ...2 hours ago - Watch PixelsUltron Online Free Putlocker - Putlocker Watch PixelsUltron movie online free full putlocker. Pixels ... Watch full length Watch Pixels for Free Online. Streaming Free Films to Watch Online including Movie Trailers and Movie Clips. Pixels is a 2015 American science … Official Watch Pixels Watch Online Download HD Full 2015 Watch Pixels Online, Download Watch Pixels , Watch Pixels , Watch Pixels Online, Pixels 2015 Movie watch Online, Pixels Movie Official … Watch Pixels Online Vioz Watch Pixels Online Putlocker Watch Pixels Online instanmovi Watch Pixels Online, Can I Watch Pixels Online, Pixels Full Free Movie, Download Pixels Online Free ',
 '&gt;&gt;&gt;ngaborong doran jeung hayam,&gt;&gt;&gt;diparaban sampeu atah,&gt;&gt;&gt;wilujeng boboran siam,&gt;&gt;&gt;mugi urang wangsul fitrah&lt;&gt;&gt;&gt;mugi urang wangsul fitrah&gt;&gt;&gt;mugi urang wangsul fitrah&gt;&gt;&gt;mugi urang wangsul fitrah',
 "**Welcome,Let's Play This Movie**",
 'het samalahet samalakanabintisamalakatir',
 'Numpak sepur nang tlatah Melayu',
 "Voir..Les Minions..complet..film..en ligne..720p, 1080p, complet HD. Voir.Les Minions.en ligne.gratuit. mn Voir Les Minions complet en ligne gratuit html Synopsis:.Voir..Les Minions.en ligne.gratuit.In.Les Minions.A.deskbound.CIA.analyst.volunteers.to.go.undercover.to.infiltrate.the.world.of.a.deadly.arms.dealer.and.Voir.Les Minions.2015.en ligne.gratuit.Voir. Voir Premium ✪ Access Download Les Minions complet complet film link film ☤ ☤ STREAMING Les Minions 2015 en ligne complet HD PUTLOCKER DVD RIP.Voir this film › Voir Les Minions le film complet qui peut être streaming et aussi des films connexes. Si on ne peut trouver le film Voir Les Minions film complet que vous cherchez, s'il vous plaît essayer de recherche en utilisant des mots clés différents par type dans la boîte de recherche ci-dessus.",
 '░░▒██░░░ ▄▀▄░░▒▐█▀▀▄ ▄▀▄ ▄▀▀░ █▀▀░░▄▀▄ █░█░░▐▌░▐▌ █▀▀ █▄░█ ▀█▀ █▀▀▄ █▀▀    █░░ █▀▀░░█▄░▄█ █▀▀ ▀ █░░ █░░ █▀▀ █░█ █▀▀▄░░█▀ ▀ █░░ █▄░▄█░░█▀▄ █▀▀░░   ▄▀ █▀▀░░█▄░▄█ ▄▀▄ ▀ ▄▀▀░░█▀▀ █▄░█░░█░░ ▀ ▄▀▀░ █▄░█ █▀▀░░▄▀▀░ █▀▀▄ ▄▀▄ ▀█▀ █░█ ▀ ▀█▀ ',
 '▒▐█▀█ █▀▀░░█▀ ▀ █░░ █▄░▄█░░█▀▀ ▄▀▀ ▀█▀░░▀█▀ █▀▀▄ ▄▀▀░░█▀▄ ▄▀▄ █▄░█ ░░ ',
 'Watch...Srimanthudu Full Movie Download Free HDQ. 5389 likes · 1155 talking about this. Srimanthudu Full Movie Download Free 1080P, Blue-Ray video.1 hour ago Watch full length Srimanthudu Movie for Free Online. Streaming Free Films to Watch Online',
 'Watch...Digging for Fire Full Movie Download Free HDQ. 5389 likes · 1155 talking about this. Digging for Fire Full Movie Download Free 1080P, Blue-Ray video.1 hour ago Watch full length Digging for Fire Movie for Free Online. Streaming Free Films to Watch Online',
 'Watch...Grandma Full Movie Download Free HDQ. 5389 likes · 1155 talking about this. Grandma Full Movie Download Free 1080P, Blue-Ray video.1 hour ago Watch full length Grandma Movie for Free Online. Streaming Free Films to Watch Online',
 'Watch...Vacation Full Movie Download Free HDQ. 5389 likes · 1155 talking about this. Vacation Full Movie Download Free 1080P, Blue-Ray video.1 hour ago  http://orcmovie.com/watch.php?movie=1524930&amp;vacation&amp;ref=s85024 Watch full length Vacation Movie for Free Online. Streaming Free Films to Watch Online',
 '█▀▀█ █▀▀█ █▀▀▄ █▀▀█ █▀▀ █▀▀█ █▀▀█ ',
 '█▀▀ ▀▀█▀▀ █▀▀█ █▀▀ █▀▀█ █▀▄▀█ \u3000 ░█▀▀█ █▀▀▄ █▀▀▄ \u3000 ▒█▀▀▄ █▀▀█ █░░░█ █▀▀▄ █░░ █▀▀█ █▀▀█ █▀▀▄ \u3000 ▒█░▒█ █░░ ▀▀█▀▀ █▀▀█ █▀▀█ ▒█░▒█ ▒█▀▀▄ \u3000 ▒█▀▀▀ █░░█ █░░ █░░ \u3000 ▒█▀▀▀█ █▀▀▄ █░░ ░▀░ █▀▀▄ █▀▀ \u3000 █░░ ░▀░ ▀█░█▀ █▀▀ \u3000 ▄▀ █▀█ █▀▀█ ▄█░ █▀▀ ▀▄ ',
 '█▀▀█ █▀▀█ █▀▀█ █▀▀ █▀▀█   ▀▀█▀▀ █▀▀█ █░░░█ █▀▀▄ █▀▀   █▀█ █▀▀█ ▀▀█▀▀ █░░█   ▒█▀▀█ █▀▀ █▀▀▄ ▀▀█▀▀ █░░█ █▀▀█ █░░█   ▒█▀▀▀ █▀▀█ █░█   ░░   ▒█▀▀▀█ █▀▀ █▀▀ ░▀░ █▀▀ ░▀░ █▀▀█ █░░   ▒█▀▀▀█ ░▀░ ▀▀█▀▀ █▀▀ ',
 '▒█▀▀▄ █▀▀█ █▀▀█ █▀▀█ █▀▀ █▀▄▀█ █▀▀█ █▀▀▄ ▄ \u3000 ▒█▄░▒█ █▀▀█ █▀▀▄ ░▀░ ▀▀█▀▀ █▀▀█ \u3000 █▀▀█ █▀▀▄ █▀▀▄ \u3000 ▀▀█▀▀ █░░█ █▀▀ \u3000 ▒█▀▀▀█ █▀▀█ █▀▀█ █▀▀ █▀▀ \u3000 ',
 '▒█▀▀▀█ ▀▀█▀▀ █▀▀█ █▀▀█ \u3000 ▒█░░▒█ █▀▀█ █▀▀█ █▀▀ ▄ \u3000 ▒█▀▀▀ █▀▀█ ░▀░ █▀▀ █▀▀█ █▀▀▄ █▀▀ \u3000 ▒█░░▒█ ▀█▀ ▀█▀ \u3000 ░░ \u3000 ▀▀█▀▀ █░░█ █▀▀ \u3000 ▒█▀▀▀ █▀▀█ █▀▀█ █▀▀ █▀▀ \u3000 ░█▀▀█ █░░░█ █▀▀█ █░█ █▀▀ █▀▀▄ █▀▀ \u3000 █▀▀█ █▀▀▄ █░░ ░▀░ █▀▀▄ █▀▀ \u3000 █▀▀ █▀▀█ █▀▀ █▀▀ \u3000 ',
 'I recently came across an advertisement that was attempting to sell synthetic data of customer purchasing habits. The company claimed that the synthetic data could be used in place of actual transactional data in order to train and test models. What are your thoughts on using synthetic data to train and test in lieu of organic data?',
 'sigmoid(x) = 1/(1+e^-x)',
 'Boltzmann energy func =  sum&lt;x,y&gt;(node[x]*node[y]*weight[x][y]',
 'Example:',
 'for i in range(len(X)):',
 '[[ 0  2  0  0  0  0  0  0  0  0  0  0]    0/2 = 0%    ',
 'using System;',
 'y_pred = model.predict(X_test)',
 'model.add(layers.Flatten())',
 'def _ei(x, gpr, y_max, xi):',
 '58 roi_gray = gray[y:y+w,x:x+h]      ',
 'class MLP_Net(torch.nn.Module):',
 'x = torch.rand((32, 1000, 256))',
 'import tensorflow_datasets as tfds',
 "countWhiteSpaces('hello world   rstats       1    2               6')",
 'library(ISLR)',
 'A B      C',
 'data &lt;- read.csv(datafilename, header=FALSE)   ',
 'Group\t    Start\t         End\t         Days',
 'year &lt;- c("1999","2002","2005","2008")',
 'test &lt;- data.frame(numbers = c(1, 2, 3), letters = c("a", "b", "c"))',
 'LogExpMean &lt;- function(x) {',
 'library(jsonlite)',
 'sh &lt;- transform(sh, avg14 = ifelse(year(sh$grp_dt) == 2014, 179177.8, 0))',
 'fit = lm(gamble ~ ., data = teengamb)',
 '# Load packages',
 'employee_index &lt;- which(minutes_with_ra$SHIFT == active_shift)',
 'library(rpart)',
 'Hello all,',
 'PWRdata &lt;- matrix(c(2.5, 2, 1052.0, 7.5, 1, 982.5, 12.5, 4, 756.9, 17.5, 4, 442.4, 22.5, 2, 230.9, 27.5, 0, 43.9), byrow = T, ncol=3)',
 'annotate("segment", x = -250, xend = -250, y = -50, yend = 315, colour = "gray50") +',
 'Subject &lt;- rep(1:10, each=2)',
 'a &lt;- c("cat", "dog", "pig", "snake")',
 'random = rnorm(100)',
 'dt.p.1 &lt;- dt.p[,.(f.rcvd = min(file.dt)',
 'Error in `[.data.table`(dt.results.wk.disc.age.bucket, , .(age.resolved.bucket,  : ',
 'MidLength = c(12,13,14,15,16,12,12,14)',
 'Error in fread(x, select = cols.to.keep, colClasses = c("Character"),  : ',
 'server&lt;- function (input, output){',
 '&gt; install.packages("swirl")',
 "df &lt;- data.frame('Dev' = 1:12,",
 'library(tidyverse)',
 'Error in fread("W:/r_201908.csv") : ',
 'urladv &lt;- "https://www.basketball-reference.com/leagues/NBA_2019_advanced.html"',
 '# Chunk 1 ',
 'mu_function &lt;- function(x) {',
 'tbl &lt;- quantmod::getSymbols("SPCE", src = "yahoo", ',
 'corr &lt;- function(directory, threshold = 0) {',
 '(mosaic.table &lt;- table(droplevels(filter(V1, Resumptiepatroon != "nvt"))$Zinstype, droplevels(filter(V1, Resumptiepatroon != "nvt"))$Resumptiepatroon, dnn=c("Zinstype","Resumptiepatroon")))',
 'm1 &lt;-matrix(c(1,0), 1,2)',
 'y &lt;- rnorm(n = 100)',
 'ms, sensor, status, id',
 'lm4 &lt;- glm(Virus ~ Sex + age + Site, family = binomial)',
 'plot(model, which = 4, id.n = 3)\t',
 'fmt_currency(',
 'indv_details &lt;- function(link){',
 'sg_data = read.table("...csv", sep = ",", header = TRUE)',
 'mean_height_and_mass &lt;- starwars %&gt;%',
 'library(survival)',
 'random &lt;- function(N,Y,xi,a,b){',
 '# Age Period Deaths Exposure',
 '&gt; table(combined$SYSTEM_SUPPLIER)',
 'Exp_plot &lt;- ggplot(data=land,aes(y=Price,x=Area))+geom_point()',
 'svyranktest(ResultA ~ IndependantVariableA, design = surveydesign, test = "wilcoxon")',
 'Beer_UsageWeekdays Beer_UsageQuarts',
 "linear_reg(mode = 'regression', penalty = varying(), mixture = 0.6) %&gt;%  ",
 'df %&gt;% ',
 "m = linear_reg(mode = 'regression', penalty = varying(), mixture = 0.6) %&gt;%",
 'IQ_model = gee(IQ_score~PGS_score+',
 'setorder(crsp, permno, date, na.last = TRUE)',
 'icc &lt;- function(b, a, c) {',
 'library(purrr)',
 'lib_nacl_v_sc_t &lt;- liberty.tribs %&gt;%                                  # Pipe in data frame',
 '# Create jar of red and blue beads ',
 '# make subsets: pick which levels of Decade to drop:',
 'count(df1, across(everything()))',
 'Number = as.integer(rep(NA,10))',
 'mediasgeral&lt;- ggplot(data = contagem_forrageamento,aes(x = Horário , y = n_de_sauvas_agosto, color = "agosto" , group = 1)) +',
 'describe(cohort1, select = -c("ID", "cohort"))',
 'test_ts = xts(testdata[,c("maxtemp")], order.by=as.Date(testdata$date))',
 'x&lt;-sample(c(1,0,NA),1000,replace=TRUE)',
 'x &lt;- c(rep(1, 250),rep(2, 250), rep(3, 250), rep(4, 250))',
 'UCB.table &lt;- margin.table(UCBAdmissions, c(1,2))',
 '&gt;http://ad.doubleclick.net/click;h=(junk here);~sscs=?http://googleads.g.doubleclick.net/aclk?sa=l&amp;ai=(junk here)&amp;adurl=http://www.papajohns.com/index.shtm?utm_source=googlenetwork&amp;utm_medium=DisplayCPC&amp;utm_campaign=GoogleRemarketing',
 <NA>,
 '&gt;Using past campaign information to target a particular message to an audience.',
 '&gt; https://www.store.yahoo.net Wat do?',
 '&gt; place your website url',
 '&gt;A discrepancy between DFP and Google Analytics (GA) is expected ',
 '&gt;because of the differences in reporting methodologies: DFP records ',
 '&gt;clicks and Google Analytics records page visits. DFP is based on ad ',
 '&gt;server logs, and is generally more accurate at reporting, and ',
 '&gt;analytics is based on cookies or page loads. Below are some ',
 '&gt;explanations why a discrepancy between DFP and Google Analytics exist.',
 '&gt;1. Different counting methodologies (server-based counting ',
 '&gt;vs. counting cookies or page loads)',
 '&gt;2. Not counting the same thing: a click in DFP is not the same ',
 '&gt;as an impression in analytics',
 '&gt;3. In case of an ad in Flash with Internet Explorer, the Referrer URL ',
 '&gt;is not provided and the origin of the user is then “blank.” In this ',
 '&gt;case, a user who clicked on a Flash ad in Internet Explorer would be, ',
 '&gt;on the landing page, considered as having typed in the URL directly ',
 '&gt;in the browser and analytics wouldn’t record the user as originating ',
 '&gt;from another website.',
 '&gt;4. Referrer URLs in analytics aren’t an accurate measure of clicks ',
 '&gt;or landings for the following reasons',
 '&gt;               a. Referrers can be disabled on most browsers',

## Test 4: Clasificacion Sentimiento

In [41]:
core.train_and_classify_sentimiento(reddit_data, reddit_data['post'][1000])

'NEGATIVE'

In [42]:
reddit_data['sentiment'][1000]

'NEGATIVE'

## Test 5: Resumenes de Texto

In [43]:
df = pd.read_csv('reddit_database_sentiment.csv', usecols=['post'],nrows=2000,sep=';')
texto = df['post']
core.post_summarisation(texto)

0                Work for an analytics software company ?
1       While in the past behavioral targetting has la...
2           Call 919-404-9233 for a 15 min consultation .
3       Here is the program details of the data analyt...
4                                                thanks .
                              ...
1995    So I 'm checking here to see if anyone 's crea...
1996    When I go to Acquisition - & gt ; Source/Mediu...
1997              Anyone have any idea what it could be ?
1998    Can I deploy this through GTM or does this inf...
1999                         Any help greatly appreciated
Length: 2000, dtype: object

In [44]:
#quiero sacar un texto con las lineas de la 9000 a la 10000
texto_2 = pd.read_csv('reddit_database_sentiment.csv', usecols=['post'],header=0,nrows=1000,skiprows=range(1,9001),sep=';')
core.post_summarisation(texto_2.post)

0      I was thinking about implementing some reinfor...
1      Hours to code , length/size of dataset to trai...
2      Any Threshold value can change the accuracy se...
3                      Will we get stuck at some point ?
4      Specifically for the face recognition they say...
                             ...
995    4 ) Also , since it is trained on a huge datas...
996                                                 Jack
997    The code is written in Keras 2.2.2 Link to Rep...
998                   I 'd greatly appreciate any help .
999    Furthermore I do not think this accuracy is to...
Length: 1000, dtype: object

In [45]:
#comprobaciones para otros textos
texto_3 = pd.read_csv('reddit_database_sentiment.csv', usecols=['post'],header=0,nrows=1000,skiprows=range(1,6001),sep=';')
core.post_summarisation(texto_3.post)

0      Maybe a website builder which allows me use go...
1      I have intermediate knowledge on SQL , Power B...
2        Does anyone have any idea why it 's happening ?
3                                                    Etc
4                I am interested to hear your thoughts .
                             ...
995    What are some of the basic insights that i sho...
996    Test B had 7 items , with an average score of ...
997    Check it out : [ https : //doordash.engineerin...
998    Again , the help needed is specifically for ju...
999                        Which is better to work for ?
Length: 1000, dtype: object

In [46]:
texto_4 = pd.read_csv('reddit_database_sentiment.csv', usecols=['post'],header=0,nrows=1000,skiprows=range(1,200000),sep=';')
core.post_summarisation(texto_4.post)

0       These signs will then be summarized in a table .
1      Hence the contaminants should also have a bino...
2      Is there a proper way mathematical way in whic...
3      In cases , where the prediction is different ,...
4      I really like the idea of working somewhere fo...
                             ...
995    And does the type of regression change how it ...
996    Is there any way that I can calculate signific...
997    Is it better to impute or simply delete cases ...
998    I have this concept of a single variable curve...
999                                               thanks
Length: 1000, dtype: object

## Test 6: Distancias entre Textos

sin preprocesar

In [47]:
import nltk
from nltk.corpus import stopwords

Lo preprocesamos

In [48]:
df = pd.read_csv('reddit_database_sentiment.csv',sep=';',nrows=1000,usecols=['post'])
text = df['post']
original = text.copy()
text = text.str.replace(r'(http[s]?://.*?)[;\)\s]', ' ', regex=True) # quitar urls
text = text.str.replace(r'(\d{3}-\d{3}-\d{4})', ' ', regex=True) # quitar numeros de telefono
text = text.str.replace(r'(\d{2}/\d{2}/\d{4})', ' ', regex=True) # quitar numeros de fechas
text = text.str.replace(r'^ {4,}(.*)|(&gt.*)|(&lt.*)|(^//.*)|(\*\*.*?\*\*)|({.*})',' ', regex=True) # quitamos codigo
text = text.str.replace(r'(\\)', ' ', regex=True)
text = text.str.replace(r'(/r/.*?)[/\]\.,\s\)\\]', ' ', regex=True)
text = text.apply(lambda x: x.lower())
text = text.str.replace(r"([^\w\s,'])",'', regex=True)
text = text.str.replace(r'(\s{2,})',' ', regex=True)
text = text.str.replace(r'(doubleclick,)',' ', regex=True)
text = text.str.replace(r'displaycpcgooglenetwork',' ', regex=True)
text = text.str.replace(r'(doubleclick,)',' ', regex=True)
text = text.str.replace(r'(doubleclick,)',' ', regex=True)
text = text.str.replace(r'(--)',' ', regex=True)
text

0      there's a lot of reasons to want to know all t...
1      i'm cross posting this from hopefully you guys...
2      dotced,a functional analytics consultant, offe...
3      here is the program details of the data analyt...
4      i decided grad school physics was not for me a...
                             ...
995    i understand properties can't be moved without...
996    hey all i have just been contracted by a natio...
997    hi gang, i've been lurking on the sub for a wh...
998    i'd like to test two different landing pages, ...
999    hi there, i've done a lot of searching online ...
Name: post, Length: 1000, dtype: object

In [51]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)
df_primeras = text[:500]
df_segundas = text[500:]
df_segundas.index = range(500)
df_comparación_textos_diferente = pd.DataFrame({'texto1':df_primeras,'texto2':df_segundas})
df_comparación_textos_diferente['distancia']= df_comparación_textos_diferente.apply(lambda x: core.texts_distance(x.loc['texto1'],x['texto2']),axis=1)
df_comparación_textos_diferente

,texto1,texto2,distancia
0,there's a lot of reasons to want to know all t...,i want to analyze the checkout conversion funn...,0.611638
1,i'm cross posting this from hopefully you guys...,"hi everyone, wondering if anyone can give me s...",0.432631
2,"dotced,a functional analytics consultant, offe...",hi reddit i have been working for 5 years in a...,0.396751
3,here is the program details of the data analyt...,i got a website with reviews of some products\...,0.556012
4,i decided grad school physics was not for me a...,"i have a responsive website, ie the mobile ver...",0.473353
...,...,...,...
495,let's say a user comes to your website from a ...,i understand properties can't be moved without...,0.797952
496,i've been assigned to write up a case study on...,hey all i have just been contracted by a natio...,0.442872
497,curious if anyone else is seeing this checked ...,"hi gang, i've been lurking on the sub for a wh...",0.681509
498,to use this feature visit eventtrackingcom i r...,"i'd like to test two different landing pages, ...",0.606496
499,register to the new devtodevs free webinar it ...,"hi there, i've done a lot of searching online ...",0.468133

In [52]:
primer_post = text[0]
df['post'] = text
df_comparación_texto_unico = df.copy()
df_comparación_texto_unico['distancia_al_primer_post '] = df_comparación_texto_unico.apply(lambda x: core.texts_distance(primer_post,x['post']),axis=1)
df_comparación_texto_unico # la primera es 0 porque es la distancia a si mismo

,post,distancia_al_primer_post
0,there's a lot of reasons to want to know all t...,0.000000
1,i'm cross posting this from hopefully you guys...,0.452532
2,"dotced,a functional analytics consultant, offe...",0.831834
3,here is the program details of the data analyt...,0.775560
4,i decided grad school physics was not for me a...,0.618458
...,...,...
995,i understand properties can't be moved without...,0.660183
996,hey all i have just been contracted by a natio...,0.650803
997,"hi gang, i've been lurking on the sub for a wh...",0.551087
998,"i'd like to test two different landing pages, ...",0.503276
999,"hi there, i've done a lot of searching online ...",0.508370